import type { Category, ComponentDefinition, PropDefinition } from './catalog';
import { chartSampleData } from './chart-samples.ts';

const p = (
  name: string,
  type: string,
  description: string,
  defaultValue?: string,
): PropDefinition => ({ name, type, description, defaultValue });
const native = [
  p('className / style', 'string / CSSProperties', 'Native styling wins over the defaults.'),
  p(
    'unstyled',
    'boolean',
    'Remove default classes while retaining semantics and behavior.',
    'false',
  ),
];
const value = [
  p(
    'value / defaultValue',
    'component value',
    'Controlled value or initial state. See the exported TypeScript interface.',
  ),
  p(
    'onValueChange',
    '(value) => void',
    'Subscribe to changes; native input events also pass through.',
  ),
];
const layout = [
  p(
    'gap / padding',
    'ResponsiveValue<number | string>',
    'Numbers use 8px units; strings accept CSS lengths. Objects support base, sm, md and lg.',
  ),
  p('asChild', 'boolean', 'Apply layout to one child without an extra wrapper.', 'false'),
];
function define(
  slug: string,
  name: string,
  category: Category,
  description: string,
  imports: string[],
  code: string,
  props: PropDefinition[],
  accessibility: string,
  extra: Partial<ComponentDefinition> = {},
): ComponentDefinition {
  return {
    slug,
    name,
    category,
    description,
    imports,
    code,
    props: [...props, ...native],
    accessibility,
    ...extra,
  };
}
const layoutA11y =
  'Layout does not add interaction semantics. Use asChild to retain native landmarks and meaningful reading order; do not visually reorder content away from its DOM order.';
const inputA11y =
  'Use a visible Field label or an aria-label. Native required, disabled, readOnly, name and form attributes pass through. Custom validation remains the application responsibility.';
const virtualA11y =
  'The viewport is keyboard-focusable with Page, Home and End scrolling. List position and total size are announced; a focused item stays mounted. Virtualization is opt-in: provide a search or nonvirtual view when every record must be discoverable by assistive technology or browser find.';
const virtualData =
  'const items = Array.from({ length: 1000 }, (_, i) => ({ id: String(i), name: `Project ${i + 1}` }));';
const chartData = `const data = ${JSON.stringify(chartSampleData, null, 2)};`;

export const extendedComponents: ComponentDefinition[] = [
  define(
    'typography',
    'Typography',
    'Typography',
    'Semantic HTML typography with native props, refs, and a restrained type scale.',
    ['H1', 'H2', 'P', 'Strong', 'Em', 'A', 'Code', 'Small', 'Blockquote', 'Ul', 'Li'],
    '<Stack gap={2}>\n  <H1>Project overview</H1>\n  <P>A clear starting point for <Strong>your next idea</Strong>.</P>\n  <H2>What matters</H2>\n  <P tone="muted" size="sm">Keep the hierarchy quiet and the content readable.</P>\n  <Blockquote>Start plain. Make it your own.</Blockquote>\n  <Ul><Li>Native semantics</Li><Li>Every direction</Li></Ul>\n  <P><Em>Built with care.</Em> Read the <A href="/docs/accessibility">accessibility guide</A>.</P>\n  <P><Code dir="ltr">@plain/ui</Code> <Small tone="muted">React and TypeScript</Small></P>\n</Stack>',
    [
      p(
        'H1 / H2 / H3 / H4 / H5 / H6',
        'native heading elements',
        'Heading level remains semantic regardless of visual size.',
      ),
      p(
        'P / Span / Small / Strong / Em / A',
        'native HTML elements',
        'Native attributes, event handlers, and element-specific refs pass through.',
      ),
      p(
        'Code / Pre / Blockquote / Ul / Ol / Li / Mark',
        'native HTML elements',
        'Semantic code, quotation, lists, and highlighted text.',
      ),
      p('tone', 'default | muted | accent | danger', 'Optional semantic foreground.', 'default'),
      p(
        'size',
        'xs | sm | md | lg | xl | 2xl | 3xl | 4xl',
        'An explicit fixed type size. Does not change the element or heading level.',
      ),
      p('weight', 'normal | medium | semibold | bold', 'Override the default text weight.'),
      p(
        'align / wrap / truncate',
        'logical alignment / text wrapping / boolean',
        'Text presentation; native style and className take precedence.',
      ),
    ],
    'Use heading levels in document order. A renders a real anchor and accepts href. Preserve the full meaning of essential content rather than truncating it. For an overflowing Pre, provide tabIndex={0}, a region role and an accessible name.',
    { entry: '@plain/ui/typography', setup: "import { Stack } from '@plain/ui/layout';" },
  ),
  define(
    'box',
    'Box',
    'Layout',
    'A native surface with responsive spacing and no imposed decoration.',
    ['Box'],
    '<Box padding={{ base: 2, md: 3 }}>Project notes</Box>',
    layout,
    layoutA11y,
  ),
  define(
    'flex',
    'Flex',
    'Layout',
    'Responsive alignment, direction and wrapping on an 8px rhythm.',
    ['Flex', 'Button'],
    '<Flex gap={2} align="center" justify="between" wrap>\n  <span>Project overview</span>\n  <Button variant="outline">Edit project</Button>\n</Flex>',
    [
      ...layout,
      p(
        'direction / align / justify',
        'ResponsiveValue',
        'Row or column direction, cross-axis alignment, and main-axis distribution.',
      ),
      p('wrap', 'boolean', 'Allow items to wrap.', 'false'),
    ],
    layoutA11y,
  ),
  define(
    'stack',
    'Stack',
    'Layout',
    'Vertical rhythm without hand-written spacing classes.',
    ['Stack'],
    '<Stack gap={2}>\n  <strong>Website redesign</strong>\n  <p>Discovery and delivery.</p>\n</Stack>',
    layout,
    layoutA11y,
  ),
  define(
    'inline',
    'Inline',
    'Layout',
    'A wrapping row for compact actions and metadata.',
    ['Inline', 'Badge'],
    '<Inline gap={1}><Badge>Design</Badge><Badge>Development</Badge><Badge>Research</Badge></Inline>',
    [...layout, p('wrap', 'boolean', 'Wrap overflowing items.', 'true')],
    layoutA11y,
  ),
  define(
    'grid',
    'Grid',
    'Layout',
    'Responsive grid tracks, auto-fit collections and a natural 12-column foundation.',
    ['Grid', 'Box'],
    '<Grid columns={{ base: 1, sm: 2, lg: 3 }} gap={2}>\n  <Box padding={2}>Research</Box><Box padding={2}>Design</Box><Box padding={2}>Build</Box>\n</Grid>',
    [
      ...layout,
      p(
        'columns',
        'ResponsiveValue<number | string>',
        'A column count or any valid CSS grid-template-columns value.',
      ),
      p(
        'minItemWidth',
        'string',
        'Use auto-fit tracks with a minimum item width instead of explicit columns.',
      ),
      p('rowGap', 'ResponsiveValue<LayoutSpace>', 'An independent row gap.'),
    ],
    layoutA11y,
  ),
  define(
    'container',
    'Container',
    'Layout',
    'Consistent content width and responsive page gutters.',
    ['Container'],
    '<Container maxWidth="64rem" gutter={{ base: 2, md: 4 }}>\n  <p>Project workspace</p>\n</Container>',
    [
      p('maxWidth', 'number | string', 'Maximum width; numeric values are pixels.', '72rem'),
      p('gutter', 'ResponsiveValue<LayoutSpace>', 'Inline page padding.'),
    ],
    layoutA11y,
  ),
  define(
    'center',
    'Center',
    'Layout',
    'Center content in both axes without changing its semantics.',
    ['Center'],
    '<Center style={{ minHeight: 120 }}>No pending tasks</Center>',
    [p('inline', 'boolean', 'Use inline-flex instead of flex.', 'false'), ...layout],
    layoutA11y,
  ),
  define(
    'spacer',
    'Spacer',
    'Layout',
    'Flexible space for toolbars or an explicit token-sized gap.',
    ['Flex', 'Spacer'],
    '<Flex align="center">\n  <span>Workspace</span><Spacer /><span>Saved</span>\n</Flex>',
    [
      p('size', 'ResponsiveValue<LayoutSpace>', 'Omit to absorb available flex space.'),
      p('axis', 'horizontal | vertical', 'Axis for explicit spacing.', 'vertical'),
    ],
    'Spacer is decorative and hidden from assistive technology. Prefer gap on a layout when separating every child.',
  ),
  define(
    'masonry',
    'Masonry',
    'Layout',
    'Responsive columns for variable-height media and repeated items.',
    ['Masonry', 'Box'],
    '<Masonry columns={{ base: 1, sm: 2, lg: 3 }} gap={2}>\n  {[80, 120, 96, 144, 88, 112].map((height, i) => (\n    <Box key={i} padding={2} style={{ minHeight: height, background: "var(--ui-muted)" }}>Item {i + 1}</Box>\n  ))}\n</Masonry>',
    [
      p('columns', 'ResponsiveValue<number>', 'Column count at each breakpoint.'),
      p('gap', 'ResponsiveValue<LayoutSpace>', 'Space between columns and items.', '2'),
    ],
    'CSS columns preserve source order down each column. Avoid masonry for content requiring a strict left-to-right sequence; use Grid instead.',
  ),
  define(
    'split-pane',
    'Split pane',
    'Layout',
    'Keyboard and pointer resizing for editor-like workspaces.',
    ['SplitPane', 'SplitPanePanel', 'SplitPaneHandle'],
    '<SplitPane style={{ height: 240 }}>\n  <SplitPanePanel defaultSize="35%" minSize="20%">Files</SplitPanePanel>\n  <SplitPaneHandle />\n  <SplitPanePanel minSize="30%">Editor</SplitPanePanel>\n</SplitPane>',
    [
      p('orientation', 'horizontal | vertical', 'Desktop resize axis.', 'horizontal'),
      p(
        'mobileOrientation / mobileBreakpoint',
        'horizontal | vertical | false / number',
        'Container-based compact arrangement; false disables adaptation.',
        'vertical / 520',
      ),
      p(
        'resizeTargetMinimumSize',
        '{ coarse: number; fine: number }',
        'Invisible pointer hit area around the hairline handle.',
        '{ coarse: 32, fine: 12 }',
      ),
      p(
        'groupRef / panelRef',
        'engine refs',
        'useGroupRef, usePanelRef and useDefaultLayout expose reset, collapse and layout persistence.',
      ),
      p(
        'defaultSize / minSize / maxSize',
        'number | string',
        'Panel sizing from react-resizable-panels; use percentage strings when intended.',
      ),
      p(
        'onLayoutChanged',
        '(layout) => void',
        'Subscribe to completed layout changes on the group.',
      ),
    ],
    'The handle is an accessible separator with keyboard resizing. Give the handle a localized aria-label and panels meaningful content headings.',
  ),
  ...(['list', 'grid', 'masonry'] as const).map((kind) =>
    define(
      `virtual-${kind}`,
      `Virtual ${kind}`,
      'Virtualization',
      `Render a window of a large ${kind} collection with measured positioning and stable keys.`,
      [kind === 'list' ? 'VirtualList' : kind === 'grid' ? 'VirtualGrid' : 'VirtualMasonry'],
      `<${kind === 'list' ? 'VirtualList' : kind === 'grid' ? 'VirtualGrid' : 'VirtualMasonry'}\n  items={items}\n  getItemKey={(item) => item.id}\n  height={320}\n  ${kind === 'grid' ? 'columns={{ base: 1, md: 2 }} rowHeight={64}' : kind === 'masonry' ? 'lanes={{ base: 1, md: 2 }} estimateSize={64}' : 'estimateSize={48}'}\n  renderItem={(item) => <div style={{ padding: 16 }}>{item.name}</div>}\n/>`,
      [
        p('items', 'readonly T[]', 'Stable collection of records.'),
        p('getItemKey', '(item: T, index: number) => Key', 'Required stable identity.'),
        p('renderItem', '(item: T, index: number) => ReactNode', 'Render each visible record.'),
        p('height', 'number | string', 'Constrained viewport height.', '400'),
        p(
          'overscan / ssrCount',
          'number',
          'Extra visible records and server-rendered fallback count.',
        ),
        p(
          kind === 'grid'
            ? 'columns / rowHeight'
            : kind === 'masonry'
              ? 'lanes / estimateSize'
              : 'estimateSize',
          'number | ResponsiveValue<number> | function',
          'Grid tracks or estimated measured item size; see the typed interface.',
        ),
      ],
      virtualA11y,
      { setup: virtualData },
    ),
  ),
  define(
    'sidebar',
    'Sidebar',
    'Navigation',
    'A collapsible desktop rail and a swipeable mobile navigation surface.',
    [
      'SidebarProvider',
      'Sidebar',
      'SidebarHeader',
      'SidebarContent',
      'SidebarGroup',
      'SidebarMenu',
      'SidebarMenuItem',
      'SidebarItem',
      'SidebarInset',
      'SidebarTrigger',
    ],
    '<SidebarProvider style={{ minHeight: 300 }}>\n  <Sidebar label="Workspace navigation">\n    <SidebarHeader>Workspace</SidebarHeader>\n    <SidebarContent><SidebarGroup label="Projects"><SidebarMenu>\n      <SidebarMenuItem><SidebarItem active>Overview</SidebarItem></SidebarMenuItem>\n      <SidebarMenuItem><SidebarItem>Projects</SidebarItem></SidebarMenuItem>\n    </SidebarMenu></SidebarGroup></SidebarContent>\n  </Sidebar>\n  <SidebarInset><SidebarTrigger /><h3>Overview</h3></SidebarInset>\n</SidebarProvider>',
    [
      p('collapsed / defaultCollapsed', 'boolean', 'Desktop state on SidebarProvider.'),
      p('mobileOpen / defaultMobileOpen', 'boolean', 'Mobile overlay state on SidebarProvider.'),
      p('mobileBreakpoint', 'number', 'Mobile threshold in pixels.', '768'),
      p('collapsible', 'icon | offcanvas | none', 'Provider collapse mode.', 'icon'),
      p('variant', 'sidebar | inset | floating', 'Sidebar surface treatment.', 'sidebar'),
      p('mobileWidth', 'string', 'Drawer width clamped to the small viewport.', '288px'),
      p(
        'shortcut',
        'string | false',
        'Provider-scoped Ctrl/Cmd shortcut; ignored during input editing.',
        'b',
      ),
      p('width / collapsedWidth', 'string', 'Provider widths or sidebar token overrides.'),
      p('side', 'start | end', 'Logical side of Sidebar.', 'start'),
      p(
        'asChild / active / closeOnSelect',
        'boolean',
        'SidebarItem composition, active state and mobile dismissal.',
      ),
    ],
    'Compose Header, Footer, Content, GroupLabel, GroupContent, GroupAction, Input, Separator, Rail, MenuButton, MenuAction, MenuBadge, MenuSub and MenuSubButton. Native links use asChild on menu buttons. Nested expansion uses P.UI Collapsible. Desktop collapse and mobile open state are separate and controllable; Vaul handles the mobile focus trap, swipe dismissal and restoration. Motion follows the theme and reduced-motion preference. Inset accepts asChild to preserve application landmarks.',
  ),
  define(
    'app-shell',
    'App shell',
    'Layout',
    'Page landmarks, a skip link and safe-area-aware mobile structure.',
    ['AppShell'],
    '<AppShell header={<header>Workspace</header>} footer={<footer>All changes saved</footer>}>\n  <h3>Project overview</h3><p>Your workspace is ready.</p>\n</AppShell>',
    [
      p(
        'header / sidebar / footer / bottomNavigation',
        'ReactNode',
        'Compose each structural area.',
      ),
      p('contentId', 'string', 'Target of the built-in skip link.'),
      p('skipLinkLabel', 'string', 'Localized skip-link text.', 'Skip to content'),
    ],
    'AppShell creates a main landmark. Do not nest it inside another main landmark. Supply semantic header, footer and navigation elements as appropriate.',
  ),
  define(
    'bottom-navigation',
    'Bottom navigation',
    'Navigation',
    'Compact mobile destinations with safe-area spacing.',
    ['BottomNavigation'],
    '<BottomNavigation defaultValue="home" items={[\n  { value: "home", label: "Home" },\n  { value: "projects", label: "Projects" },\n  { value: "account", label: "Account" },\n]} />',
    [
      p(
        'items',
        'BottomNavigationItem[]',
        'Destination values, labels, icons, hrefs and disabled states.',
      ),
      ...value,
      p('fixed', 'boolean', 'Fix to the viewport bottom.', 'false'),
    ],
    'Renders a named navigation landmark. Items with href use native links; selection exposes aria-current. Keep destinations few and labels short.',
  ),
  define(
    'stepper',
    'Stepper',
    'Navigation',
    'A clear, controllable sequence through multi-step flows.',
    ['Stepper'],
    '<Stepper defaultValue="details" steps={[\n  { value: "details", label: "Details" },\n  { value: "team", label: "Team" },\n  { value: "review", label: "Review" },\n]} />',
    [
      p('steps', 'StepperStep[]', 'Values, labels, descriptions, icons and disabled states.'),
      ...value,
      p('orientation', 'horizontal | vertical', 'Sequence direction.', 'horizontal'),
      p('linear', 'boolean', 'Restrict forward navigation to the next step.'),
    ],
    'The current step uses aria-current=step. Step buttons remain keyboard-operable. Validate and render step content in the application.',
  ),
  define(
    'segmented-control',
    'Segmented control',
    'Forms',
    'One choice from a small, visible set.',
    ['SegmentedControl'],
    '<SegmentedControl aria-label="Reporting interval" defaultValue="week" options={[\n  { value: "day", label: "Day" }, { value: "week", label: "Week" }, { value: "month", label: "Month" },\n]} />',
    [
      p('options', 'SegmentedControlOption[]', 'Values, labels, icons and disabled choices.'),
      ...value,
      p(
        'name / required / disabled',
        'native radio attributes',
        'Form participation and validation.',
      ),
    ],
    'Radix RadioGroup provides roving focus and arrow-key selection with RTL-aware direction. Label the group, not just individual options.',
  ),
  define(
    'tree-view',
    'Tree view',
    'Navigation',
    'A hierarchical explorer with full directional keyboard navigation.',
    ['TreeView'],
    '<TreeView aria-label="Project files" defaultExpandedIds={["project"]} nodes={[\n  { id: "project", label: "Website", children: [\n    { id: "design", label: "Design files" }, { id: "source", label: "Source code" },\n  ] },\n]} />',
    [
      p('nodes', 'TreeNode[]', 'Stable ids, labels, children, icons and disabled states.'),
      p('selectedId / onSelectionChange', 'string / callback', 'Selected item state.'),
      p('expandedIds / onExpandedChange', 'readonly string[] / callback', 'Expanded branches.'),
      p(
        'defaultSelectedId / defaultExpandedIds',
        'string / readonly string[]',
        'Initial uncontrolled states.',
      ),
    ],
    'Uses tree and treeitem roles, selection and expansion states. Arrow keys, Home, End and typeahead move focus. Expansion directions mirror in RTL.',
  ),
  define(
    'number-input',
    'Number input',
    'Forms',
    'A native numeric field with optional, bounded stepping.',
    ['Field', 'NumberInput'],
    '<Field label="Seats"><NumberInput defaultValue={5} min={1} max={100} name="seats" /></Field>',
    [
      ...value,
      p(
        'min / max / step',
        'number / number / number | any',
        'Native numeric constraints and control increments.',
      ),
      p('showControls', 'boolean', 'Show decrement and increment actions.', 'true'),
    ],
    inputA11y,
  ),
  define(
    'search-input',
    'Search input',
    'Forms',
    'Search semantics, a stable clear action and native form behavior.',
    ['Field', 'SearchInput'],
    '<Field label="Search projects"><SearchInput placeholder="Find a project..." name="search" /></Field>',
    [
      ...value,
      p('onClear', '() => void', 'Called after the clear action.'),
      p('clearLabel', 'string', 'Localized clear-button name.', 'Clear search'),
    ],
    inputA11y,
  ),
  define(
    'password-input',
    'Password input',
    'Forms',
    'A password field with an accessible visibility toggle.',
    ['Field', 'PasswordInput'],
    '<Field label="Password"><PasswordInput name="password" autoComplete="new-password" required /></Field>',
    [
      ...value,
      p('visible / defaultVisible', 'boolean', 'Controlled or initial reveal state.'),
      p('onVisibilityChange', '(visible: boolean) => void', 'Subscribe to the reveal state.'),
    ],
    `${inputA11y} The toggle announces Show/Hide password and aria-pressed.`,
  ),
  define(
    'pin-input',
    'PIN input',
    'Forms',
    'A single native input with visually separated code slots.',
    ['Field', 'PinInput'],
    '<Field label="Verification code"><PinInput length={6} name="code" required /></Field>',
    [
      ...value,
      p('length', 'number', 'Number of slots, clamped to 1-32.', '6'),
      p('numeric / masked', 'boolean', 'Digit-only input and optional masking.'),
      p('onComplete', '(value: string) => void', 'Called when a new complete code is entered.'),
    ],
    'A single labeled native input preserves paste, autofill, selection and editing. Decorative slots are hidden from assistive technology. autoComplete=one-time-code is supported.',
  ),
  define(
    'file-upload',
    'File upload',
    'Forms',
    'Native file selection with drag-and-drop and explicit validation.',
    ['FileUpload'],
    '<FileUpload aria-label="Upload project documents" accept=".pdf,.txt" multiple maxFiles={5} maxSize={5000000} name="documents" />',
    [
      ...value,
      p('accept / multiple', 'string / boolean', 'Native file constraints.'),
      p('maxFiles / maxSize', 'number', 'Maximum count and bytes per file.'),
      p('onFilesChange', '(files: File[]) => void', 'Accepted file selection.'),
      p(
        'onReject',
        '(rejections: FileUploadRejection[]) => void',
        'Rejected files with type, size or count reasons.',
      ),
    ],
    `${inputA11y} Drag-and-drop has a native picker alternative. Client validation does not replace server validation.`,
  ),
  define(
    'color-picker',
    'Color picker',
    'Forms',
    'A themed color surface with editable hex, hue and RGB controls.',
    ['Field', 'ColorPicker'],
    '<Field label="Project color"><ColorPicker defaultValue="#087f5b" swatches={["#087f5b", "#2563eb", "#be185d"]} name="color" /></Field>',
    [
      ...value,
      p('swatches', 'readonly string[]', 'Preset hex colors.'),
      p('pickerLabel', 'string', 'Accessible name of the color popover.', 'Choose color'),
    ],
    inputA11y,
  ),
  define(
    'rating',
    'Rating',
    'Forms',
    'Star ratings with radio semantics and keyboard selection.',
    ['Rating'],
    '<Rating aria-label="Rate your experience" defaultValue={4} max={5} name="rating" />',
    [
      ...value,
      p('max', 'number', 'Maximum rating.', '5'),
      p('readOnly / allowClear', 'boolean', 'Display-only mode or clearable selection.'),
      p('getLabel', '(value, max) => string', 'Localize each rating option.'),
    ],
    'Editable ratings are a labeled radio group. Read-only ratings expose a readable value rather than interactive controls. Arrow keys follow reading direction.',
  ),
  define(
    'tags-input',
    'Tags input',
    'Forms',
    'Editable tokens with native text entry, paste and removal.',
    ['Field', 'TagsInput'],
    '<Field label="Project tags"><TagsInput defaultValue={["design", "research"]} maxTags={8} name="tags" placeholder="Add a tag..." /></Field>',
    [
      ...value,
      p('maxTags', 'number', 'Maximum accepted tags.'),
      p('delimiters', 'readonly string[]', 'Commit separators.', 'Enter, comma'),
      p('addOnBlur', 'boolean', 'Commit pending text on blur.'),
    ],
    `${inputA11y} Each tag has a named remove action. Escape, Backspace and separators support text editing.`,
  ),
  define(
    'multi-select',
    'Multi-select',
    'Forms',
    'Searchable multiple choices with selected chips and form values.',
    ['Field', 'MultiSelect'],
    '<Field label="Team"><MultiSelect defaultValue={["design"]} name="team" options={[\n  { value: "design", label: "Design" }, { value: "engineering", label: "Engineering" }, { value: "research", label: "Research" },\n]} /></Field>',
    [
      p('options', 'MultiSelectOption[]', 'Values, labels, icons and disabled choices.'),
      ...value,
      p('maxSelected', 'number', 'Maximum selected values.'),
      p('open / onOpenChange', 'boolean / callback', 'Control the options popover.'),
    ],
    'Labeled combobox and multiselect listbox semantics connect input, popup and active option. Arrow keys, Enter and Escape operate the list; selected chips have named remove actions.',
  ),
  define(
    'menubar',
    'Menubar',
    'Navigation',
    'Desktop-style command menus with composable submenus and options.',
    [
      'Menubar',
      'MenubarMenu',
      'MenubarTrigger',
      'MenubarContent',
      'MenubarItem',
      'MenubarSeparator',
    ],
    '<Menubar>\n  <MenubarMenu><MenubarTrigger>File</MenubarTrigger><MenubarContent>\n    <MenubarItem>New project</MenubarItem><MenubarItem>Open project</MenubarItem>\n    <MenubarSeparator /><MenubarItem>Export</MenubarItem>\n  </MenubarContent></MenubarMenu>\n</Menubar>',
    [
      p('value / onValueChange', 'string / callback', 'Open menu state.'),
      p('onSelect / disabled', 'callback / boolean', 'Menu item behavior.'),
      p(
        'shortcut',
        'ReactNode',
        'Visual shortcut on MenubarItem; does not register a keyboard shortcut.',
      ),
    ],
    'Radix provides menubar keyboard behavior, typeahead, roving focus and submenu direction. Items are commands, not arbitrary content.',
  ),
  define(
    'context-menu',
    'Context menu',
    'Overlays',
    'Contextual commands on right-click or touch long-press.',
    ['ContextMenu', 'ContextMenuTrigger', 'ContextMenuContent', 'ContextMenuItem'],
    '<ContextMenu>\n  <ContextMenuTrigger><div tabIndex={0} style={{ padding: 32 }}>Project workspace</div></ContextMenuTrigger>\n  <ContextMenuContent><ContextMenuItem>Open project</ContextMenuItem><ContextMenuItem>Duplicate</ContextMenuItem></ContextMenuContent>\n</ContextMenu>',
    [
      p('onOpenChange', '(open: boolean) => void', 'Menu visibility changes.'),
      p('onSelect / disabled', 'callback / boolean', 'Menu item behavior.'),
    ],
    'Radix supplies keyboard navigation and focus restoration. Essential commands must also be available through visible controls; a context menu is a supplementary path.',
  ),
  define(
    'hover-card',
    'Hover card',
    'Overlays',
    'Optional contextual information without interrupting navigation.',
    ['HoverCard', 'HoverCardTrigger', 'HoverCardContent'],
    '<HoverCard>\n  <HoverCardTrigger asChild><a href="#profile">Alex Morgan</a></HoverCardTrigger>\n  <HoverCardContent><strong>Alex Morgan</strong><p>Product designer</p></HoverCardContent>\n</HoverCard>',
    [
      p('open / onOpenChange', 'boolean / callback', 'Controlled visibility.'),
      p('openDelay / closeDelay', 'number', 'Hover timings in milliseconds.'),
    ],
    'Hover cards are supplementary, not an accessible replacement for a profile page or popover. Put essential information on the linked destination. Trigger links retain native keyboard behavior.',
  ),
  define(
    'timeline',
    'Timeline',
    'Feedback',
    'Ordered activity with timestamps and optional custom content.',
    ['Timeline'],
    '<Timeline items={[\n  { id: "1", title: "Project created", time: "09:00", dateTime: "2026-10-01T09:00", description: "Alex started the workspace." },\n  { id: "2", title: "Design approved", time: "10:30", dateTime: "2026-10-01T10:30" },\n]} />',
    [
      p('items', 'readonly TimelineEvent[]', 'Data-driven events with stable ids.'),
      p('children', 'ReactNode', 'Alternatively compose TimelineItem parts.'),
    ],
    'Uses an ordered list with semantic time elements. Supply machine-readable dateTime values for displayed timestamps.',
  ),
  define(
    'banner',
    'Banner',
    'Feedback',
    'Inline notices with an optional action and dismissal.',
    ['Banner'],
    '<Banner title="Scheduled maintenance" variant="info" dismissible>October 12, 02:00-03:00 UTC.</Banner>',
    [
      p('variant', 'info | success | warning | danger', 'Notice treatment.', 'info'),
      p('title / action', 'ReactNode', 'Heading and optional action.'),
      p('dismissible', 'boolean', 'Show a named dismiss button.'),
      p('open / defaultOpen / onOpenChange', 'boolean / boolean / callback', 'Visibility state.'),
    ],
    'Informational notices use status; warnings and danger use alert. Reserve assertive notices for genuinely urgent updates.',
  ),
  define(
    'loading-overlay',
    'Loading overlay',
    'Feedback',
    'A busy state that preserves content dimensions and blocks interaction.',
    ['LoadingOverlay', 'Button'],
    '<LoadingOverlay label="Saving changes" visible style={{ minHeight: 160 }}>\n  <Button>Save project</Button>\n</LoadingOverlay>',
    [
      p('visible', 'boolean', 'Display loading treatment and mark content inert.', 'true'),
      p('label', 'string', 'Screen-reader status.', 'Loading'),
    ],
    'Marks the region aria-busy and its content inert while showing an announced status. Manage application focus before hiding a focused control.',
  ),
  define(
    'time-picker',
    'Time picker',
    'Scheduling',
    'Keyboard-editable time with a styled picker, constraints and form participation.',
    ['Field', 'TimePicker'],
    '<Field label="Start time"><TimePicker defaultValue="09:00" min="08:00" max="18:00" name="startTime" /></Field>',
    [
      ...value,
      p(
        'min / max / step',
        'string / string / number',
        'Native wall-time constraints; step is seconds.',
      ),
      p('clearable / clearLabel', 'boolean / string', 'Optional clear action.'),
      p(
        'minuteStep / hourCycle',
        'number / 12 | 24',
        'Picker interval and display format; native step remains in seconds.',
        '15 / 24',
      ),
    ],
    inputA11y,
    {
      usage:
        'Values are local wall-time strings, not UTC instants. Overnight ranges require an explicit application policy.',
    },
  ),
  define(
    'time-range-picker',
    'Time range picker',
    'Scheduling',
    'Two connected time controls with range validation.',
    ['TimeRangePicker'],
    '<TimeRangePicker aria-label="Office hours" defaultValue={{ from: "09:00", to: "17:00" }} fromName="opens" toName="closes" />',
    [
      ...value,
      p('fromLabel / toLabel', 'string', 'Localized field labels.'),
      p('fromName / toName', 'string', 'Independent submitted values.'),
      p('allowOvernight', 'boolean', 'Permit an end before start to mean the following day.'),
    ],
    'Each native control has a distinct visible label. Invalid ordering participates in native form validation and exposes an error message.',
  ),
  define(
    'date-range-picker',
    'Date range picker',
    'Scheduling',
    'An accessible month calendar for a complete date interval.',
    ['Field', 'DateRangePicker'],
    '<Field label="Project dates"><DateRangePicker defaultValue={{ from: new Date(2026, 9, 5), to: new Date(2026, 9, 12) }} fromName="from" toName="to" /></Field>',
    [
      ...value,
      p('min / max', 'Date | string', 'Date boundaries.'),
      p('minNights / maxNights', 'number', 'Permitted range length.'),
      p('disabledDates', 'Matcher | Matcher[]', 'DayPicker exclusion rules.'),
      p(
        'calendarProps',
        'PickerCalendarProps',
        'Locale, displayed months and calendar constraints.',
      ),
      p('fromName / toName', 'string', 'Local YYYY-MM-DD form values.'),
    ],
    'The trigger opens a keyboard-accessible range calendar. Selection and range state are announced; focus returns to the trigger on close.',
  ),
  define(
    'date-time-picker',
    'Date time picker',
    'Scheduling',
    'Local date and time with a styled calendar, time controls and timezone validation.',
    ['Field', 'DateTimePicker'],
    '<Field label="Meeting"><DateTimePicker defaultValue="2026-10-05T09:30" name="meeting" timeZone="Africa/Cairo" /></Field>',
    [
      ...value,
      p(
        'minuteStep / hourCycle',
        'number / 12 | 24',
        'Time picker interval and display format.',
        '15 / 24',
      ),
      p('min / max', 'string', 'Wall-time bounds in YYYY-MM-DDTHH:mm format.'),
      p(
        'timeZone / disambiguation',
        'IANA zone / compatible | earlier | later | reject',
        'Validate DST ambiguities using Temporal; does not convert values to instants.',
      ),
      p(
        'showCalendar / disabledDates',
        'boolean / Matcher',
        'Optional date selection and excluded dates.',
      ),
    ],
    inputA11y,
    {
      usage:
        'The value remains a wall-time string. Convert it deliberately using your IANA timezone and disambiguation policy when storing an instant.',
    },
  ),
  define(
    'date-time-range-picker',
    'Date time range picker',
    'Scheduling',
    'Paired date-time entry with consistent validation and clearing.',
    ['DateTimeRangePicker'],
    '<DateTimeRangePicker aria-label="Maintenance window" defaultValue={{ from: "2026-10-05T09:00", to: "2026-10-05T17:00" }} fromName="starts" toName="ends" />',
    [
      ...value,
      p('fromLabel / toLabel / fromName / toName', 'string', 'Labels and submitted field names.'),
      p(
        'timeZone / disambiguation',
        'string / policy',
        'Shared timezone validation, without implicit conversion.',
      ),
      p('min / max / disabledDates', 'native bounds / Matcher', 'Shared field constraints.'),
    ],
    'Each field is labeled and the interval is validated. Use an explicit timezone in applications spanning locations; ambiguous local times require a deliberate policy.',
  ),
  define(
    'full-calendar',
    'Full calendar',
    'Scheduling',
    'A responsive scheduling workspace with month, week, day and agenda views.',
    ['FullCalendar', 'type FullCalendarEvent'],
    '<FullCalendar defaultView="month" defaultDate="2026-10-05" events={events} editable\n  onEventsChange={setEvents} printFooter={<p>Studio schedule</p>} />',
    [
      p(
        'view / defaultView / onViewChange',
        'month | week | day | agenda',
        'Controlled or initial view.',
      ),
      p(
        'date / defaultDate / onDateChange',
        'CalendarDate / callback',
        'ISO date or instant; callback returns the focused ISO date.',
      ),
      p(
        'events / onEventsChange',
        'readonly FullCalendarEvent[] / callback',
        'Application-owned events with stable IDs and exclusive ends.',
      ),
      p(
        'onSlotSelect / onEventClick / onEventChange',
        'callback',
        'Create, inspect and accept move/resize requests.',
      ),
      p(
        'selectable / editable',
        'boolean',
        'Enable slot selection and event editing; edit callbacks are required.',
      ),
      p(
        'renderEvent / renderDay / toolbar / toolbarActions',
        'render functions / ReactNode',
        'Own content without replacing the scheduling model.',
      ),
      p(
        'printable / printMode / renderPrint / onPrint',
        'boolean / agenda | calendar / callbacks',
        'Print the visible range, add content, or replace printing with a PDF workflow.',
      ),
      p(
        'timeZone / locale / weekStartsOn',
        'string / string / 0-6',
        'Date interpretation, formatting and week convention.',
      ),
      p(
        'dayStart / dayEnd / slotMinutes / mobileBreakpoint',
        'number',
        'Time grid and container-responsive layout.',
      ),
    ],
    'Date grids support arrow, Home/End and Page keys with RTL handling. Events are keyboard-focusable; Alt plus arrows moves an editable event, and Shift+Alt up/down resizes it. Offer a visible event editor for touch and assistive-technology users. No scheduling backend or recurrence engine is implied.',
    {
      entry: '@plain/ui/full-calendar',
      stylesheet: '@plain/ui/full-calendar.css',
      setup: 'import * as React from "react";',
      functionSetup:
        'const [events, setEvents] = React.useState<FullCalendarEvent[]>([\n  { id: "kickoff", title: "Project kickoff", start: "2026-10-05T09:00", end: "2026-10-05T10:00" },\n  { id: "review", title: "Design review", start: "2026-10-12T14:00", end: "2026-10-12T15:00" },\n]);',
      usage:
        'Import the optional stylesheet. Events belong to your application; wire callbacks to validation, permissions and persistence. The 0.2 engine options/plugins are replaced by this P.UI API.',
    },
  ),
  ...(['area', 'bar', 'line'] as const).map((kind) =>
    define(
      `${kind}-chart`,
      `${kind[0].toUpperCase() + kind.slice(1)} chart`,
      'Charts',
      `A responsive Recharts ${kind} visualization with theme roles and a readable data alternative.`,
      [`${kind[0].toUpperCase() + kind.slice(1)}Chart`],
      `<${kind[0].toUpperCase() + kind.slice(1)}Chart data={data} index="month" label="Monthly revenue and costs" height={280}\n  series={[{ dataKey: "revenue", label: "Revenue" }, { dataKey: "costs", label: "Costs"${kind === 'line' ? ', strokeDasharray: "4 4"' : ''} }]} legend />`,
      [
        p(
          'data / index / series',
          'ChartDatum[] / string / ChartSeries[]',
          'Records, x-axis key and visible value series.',
        ),
        p('height', 'CSS height', 'Stable chart viewport.', '300'),
        p(
          'grid / legend / tooltip',
          'boolean | native Recharts props',
          'Hide an aid or configure its native props.',
          'true',
        ),
        p(
          'xAxis / yAxis',
          'boolean | XAxisProps / YAxisProps',
          'Axis visibility, format, spacing and orientation.',
          'true',
        ),
        p(
          'stacked',
          'boolean',
          'Stack visible series; explicit series stackId values take precedence.',
          'false',
        ),
        ...(kind === 'bar'
          ? []
          : [p('curve', 'Recharts curve type', 'Change interpolation.', 'monotone')]),
        p('valueFormatter', '(value: number) => string', 'Format values consistently.'),
        p('dataTable', 'sr-only | visible | false', 'Accessible data alternative.', 'sr-only'),
        p('animate / loading / empty', 'boolean', 'Motion and state controls.'),
      ],
      'Charts expose Recharts keyboard navigation and a semantic data table. Give the chart a useful label; keep series distinguishable beyond color. Motion respects the library policy.',
      { entry: '@plain/ui/charts', stylesheet: '@plain/ui/charts.css', setup: chartData },
    ),
  ),
  define(
    'donut-chart',
    'Donut chart',
    'Charts',
    'Part-to-whole values with distinct series roles and an accessible table.',
    ['DonutChart'],
    '<DonutChart label="Projects by status" height={280} innerRadius="64%" outerRadius="88%" legend data={[\n  { name: "Active", value: 18 }, { name: "Review", value: 8 }, { name: "Complete", value: 24 },\n]} />',
    [
      p('data / nameKey / valueKey', 'ChartDatum[] / string / string', 'Slice records and keys.'),
      p('innerRadius / outerRadius', 'number | string', 'Donut dimensions.'),
      p(
        'legend / tooltip / dataTable',
        'boolean | native Recharts props / boolean | native Recharts props / table policy',
        'Legends and accessible data alternatives.',
      ),
      p(
        'height / animate / loading / empty',
        'CSS height / boolean',
        'Viewport, motion and states.',
      ),
    ],
    'A semantic data table is supplied by default. Use names and values for each slice; avoid conveying distinctions only through color.',
    { entry: '@plain/ui/charts', stylesheet: '@plain/ui/charts.css' },
  ),
  define(
    'motion',
    'Motion',
    'Motion',
    'Optional layout, presence and spring motion with restrained defaults.',
    ['MotionProvider', 'Motion', 'Presence', 'springPresets'],
    '<MotionProvider>\n  <Presence><Motion preset="slide" layout transition={springPresets.gentle}>\n    <p>All changes saved.</p>\n  </Motion></Presence>\n</MotionProvider>',
    [
      p('preset', 'fade | slide | scale', 'Entry and exit defaults.', 'fade'),
      p('layout / layoutId', 'Motion props', 'Optional layout animation and shared identity.'),
      p(
        'initial / animate / exit / transition',
        'Motion props',
        'Override animation targets and timing.',
      ),
      p('duration', 'number', 'Default duration in seconds on MotionProvider.', '0.2'),
    ],
    'Uses the shared motion policy and prefers-reduced-motion. Keep critical content independent of animation; reduced motion disables entry and exit travel. Use MotionProvider to load features lazily.',
    { entry: '@plain/ui/motion' },
  ),
];
