import { writeFile } from 'node:fs/promises';
import {
  lightTokens,
  darkTokens,
  componentTokenAliases,
  paletteTones,
  tokenVariable,
} from '../src/ui/token-contract.ts';

const families = ['primary', 'secondary', 'tertiary', 'neutral', 'neutral-variant', 'error'];
const neutralPaletteTokens = Object.fromEntries(
  families.flatMap((name) =>
    paletteTones.map((tone) => {
      const channel = Math.round(tone * 2.55)
        .toString(16)
        .padStart(2, '0');
      return [`palette.${name}.${tone}`, `#${channel.repeat(3)}`];
    }),
  ),
);
await writeFile(
  new URL('../src/ui/neutral-palette.ts', import.meta.url),
  `// Generated by scripts/generate-tokens.mjs.\nimport type { ThemeTokens } from './token-contract';\nexport const neutralPaletteTokens = ${JSON.stringify(neutralPaletteTokens, null, 2)} satisfies ThemeTokens;\n`,
);
const declarations = (tokens) =>
  Object.entries(tokens)
    .map(([key, value]) => `  ${tokenVariable(key)}: ${value};`)
    .join('\n');
const derived = Object.fromEntries(
  Object.entries(lightTokens).filter(([, value]) => value.includes('var(')),
);
const css = `/* Generated from token-contract.ts. */
:root, :where([data-ui-theme-scope][data-theme='light']) {
${declarations({ ...lightTokens, ...neutralPaletteTokens })}
  color-scheme: light;
}
[data-theme='dark'] {
${declarations(darkTokens)}
  color-scheme: dark;
}
:root, :where([data-ui-theme-scope]) {
${declarations(derived)}
${declarations(componentTokenAliases)}
}
[data-density='compact'] { --ui-control-height: 32px; }
[data-density='spacious'] { --ui-control-height: 48px; }
[data-borders='none'], [data-borders='none'] :where([data-ui-theme-scope]) {
  --ui-border: transparent;
  --ui-control-border: transparent;
  --ui-input-border: transparent;
  --ui-border-width: 0px;
}
[data-borders='strong'] {
  --ui-border: var(--ui-outline);
  --ui-control-border: var(--ui-outline);
  --ui-border-width: 1px;
}
[data-motion='none'], [data-motion='reduced'] { --ui-motion-scale: 0; }
@media (prefers-reduced-motion: reduce) {
  :root, :where([data-ui-theme-scope]) { --ui-motion-scale: 0; }
}
`;
await writeFile(new URL('../src/ui/tokens.css', import.meta.url), css);
