export const lightTokens = {
  background: '#ffffff',
  foreground: '#202321',
  surface: '#ffffff',
  'surface-lowest': '#ffffff',
  'surface-low': '#fafafa',
  'surface-container': '#f5f6f5',
  'surface-high': '#f2f3f2',
  'surface-highest': '#e5e7e6',
  'surface-foreground': 'var(--ui-foreground)',
  muted: '#f5f6f5',
  'muted-foreground': '#666b68',
  outline: '#858e87',
  border: '#e5e7e6',
  'control-border': 'var(--ui-outline)',
  'input-border': 'var(--ui-control-border)',
  'border-width': '1px',
  primary: '#252826',
  'primary-foreground': '#ffffff',
  'primary-container': '#f2f3f2',
  'primary-container-foreground': '#252826',
  secondary: '#666b68',
  'secondary-foreground': '#ffffff',
  'secondary-container': '#f5f6f5',
  'secondary-container-foreground': '#202321',
  tertiary: '#666b68',
  'tertiary-foreground': '#ffffff',
  'tertiary-container': '#f5f6f5',
  'tertiary-container-foreground': '#202321',
  accent: 'var(--ui-primary)',
  'accent-foreground': 'var(--ui-primary-foreground)',
  'accent-soft': 'var(--ui-primary-container)',
  'accent-soft-foreground': 'var(--ui-primary-container-foreground)',
  danger: '#bd2436',
  'danger-foreground': '#ffffff',
  'danger-soft': '#fff0f1',
  'danger-soft-foreground': '#790e20',
  success: '#206a42',
  'success-foreground': '#ffffff',
  'success-soft': '#e9f7ee',
  warning: '#805b08',
  'warning-foreground': '#ffffff',
  'warning-soft': '#fff4da',
  info: '#265e9b',
  'info-foreground': '#ffffff',
  'info-soft': '#edf4ff',
  inverse: '#202321',
  'inverse-foreground': '#ffffff',
  'inverse-muted': '#b6bcb9',
  'inverse-accent': '#e6ebe7',
  overlay: '#11171366',
  'focus-ring': 'var(--ui-primary)',
  radius: '6px',
  'radius-sm': 'calc(var(--ui-radius) * 0.66)',
  'radius-lg': 'calc(var(--ui-radius) * 1.5)',
  'control-height': '40px',
  font: "'Inter Variable', Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  shadow: '0 8px 32px #101a1212, 0 2px 8px #101a1208',
  'shadow-sm': '0 2px 8px #101a1208',
  'shadow-lg': '0 16px 48px #101a121c',
  'duration-fast': '120ms',
  'duration-normal': '200ms',
  'duration-slow': '320ms',
  'duration-long': '480ms',
  'ease-standard': 'cubic-bezier(0.2, 0, 0, 1)',
  'ease-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
  'ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
  'motion-scale': '1',
  'layer-dropdown': '100',
  'layer-overlay': '80',
  'layer-dialog': '90',
  'layer-toast': '110',
  'chart-1': '#3e6250',
  'chart-2': '#58748d',
  'chart-3': '#927037',
  'chart-4': '#855769',
  'chart-5': '#786a91',
  'chart-6': '#397781',
  'chart-7': '#6c7546',
  'chart-8': '#8e6253',
  'chart-grid': 'var(--ui-border)',
  'chart-label': 'var(--ui-muted-foreground)',
  'space-0': '0px',
  'space-0-5': '4px',
  'space-1': '8px',
  'space-2': '16px',
  'space-3': '24px',
  'space-4': '32px',
  'space-5': '40px',
  'space-6': '48px',
  'space-8': '64px',
  'space-10': '80px',
  'space-12': '96px',
} as const;

export const darkTokens: Partial<Record<keyof typeof lightTokens, string>> = {
  background: '#141615',
  foreground: '#edeff0',
  surface: '#1b1e1c',
  'surface-lowest': '#101211',
  'surface-low': '#191c1a',
  'surface-container': '#242825',
  'surface-high': '#292e2b',
  'surface-highest': '#333a35',
  muted: '#242825',
  'muted-foreground': '#a2aaa5',
  outline: '#666f69',
  border: '#333a35',
  primary: '#e6ebe7',
  'primary-foreground': '#171a18',
  'primary-container': '#292e2b',
  'primary-container-foreground': '#e6ebe7',
  secondary: '#a2aaa5',
  'secondary-foreground': '#171a18',
  'secondary-container': '#242825',
  'secondary-container-foreground': '#edeff0',
  tertiary: '#a2aaa5',
  'tertiary-foreground': '#171a18',
  'tertiary-container': '#242825',
  'tertiary-container-foreground': '#edeff0',
  danger: '#ff8796',
  'danger-foreground': '#650b20',
  'danger-soft': '#3a2028',
  'danger-soft-foreground': '#ffdbe0',
  success: '#93dbad',
  'success-foreground': '#153c27',
  'success-soft': '#1c3a28',
  warning: '#eacb83',
  'warning-foreground': '#3d2e0c',
  'warning-soft': '#3c321d',
  info: '#a0c9fa',
  'info-foreground': '#133252',
  'info-soft': '#1a3048',
  inverse: '#edeff0',
  'inverse-foreground': '#141615',
  'inverse-muted': '#666b68',
  'inverse-accent': '#252826',
  overlay: '#00000099',
  shadow: '0 12px 36px #00000040',
  'shadow-sm': '0 2px 8px #00000024',
  'shadow-lg': '0 20px 56px #00000066',
  'chart-1': '#9ed5b5',
  'chart-2': '#a0c9ee',
  'chart-3': '#e8c882',
  'chart-4': '#edaec6',
  'chart-5': '#c7b5eb',
  'chart-6': '#8fd1db',
  'chart-7': '#bdcf90',
  'chart-8': '#e3b49f',
};

// Aliases are re-declared at every scope so they resolve against local root roles.
export const componentTokenAliases = {
  'typography.font': 'var(--ui-font)',
  'typography.foreground': 'inherit',
  'typography.muted': 'var(--ui-muted-foreground)',
  'typography.heading-weight': '600',
  'button.background': 'var(--ui-foreground)',
  'button.foreground': 'var(--ui-background)',
  'button.border': 'var(--ui-border)',
  'button.radius': 'var(--ui-radius)',
  'button.height': 'var(--ui-control-height)',
  'button.hover': 'var(--ui-muted)',
  'input.background': 'var(--ui-surface)',
  'input.foreground': 'var(--ui-foreground)',
  'input.border': 'var(--ui-control-border)',
  'input.radius': 'var(--ui-radius)',
  'input.height': 'var(--ui-control-height)',
  'input.placeholder': 'var(--ui-muted-foreground)',
  'input.focus': 'var(--ui-focus-ring)',
  'card.background': 'var(--ui-surface)',
  'card.foreground': 'var(--ui-foreground)',
  'card.border': 'var(--ui-border)',
  'card.radius': 'var(--ui-radius)',
  'panel.background': 'var(--ui-surface)',
  'panel.foreground': 'var(--ui-foreground)',
  'panel.border': 'var(--ui-border)',
  'panel.radius': 'var(--ui-radius)',
  'sidebar.background': 'var(--ui-background)',
  'sidebar.foreground': 'var(--ui-foreground)',
  'sidebar.border': 'var(--ui-border)',
  'sidebar.muted': 'var(--ui-muted-foreground)',
  'sidebar.accent': 'var(--ui-muted)',
  'sidebar.accent-foreground': 'var(--ui-foreground)',
  'sidebar.radius': 'var(--ui-radius)',
  'sidebar.width': '248px',
  'sidebar.collapsed-width': '64px',
  'navigation.background': 'var(--ui-background)',
  'navigation.foreground': 'var(--ui-foreground)',
  'navigation.border': 'var(--ui-border)',
  'navigation.active': 'var(--ui-primary-container)',
  'navigation.active-foreground': 'var(--ui-primary-container-foreground)',
  'navigation.radius': 'var(--ui-radius)',
  'tabs.background': 'var(--ui-muted)',
  'tabs.foreground': 'var(--ui-muted-foreground)',
  'tabs.active': 'var(--ui-surface)',
  'tabs.active-foreground': 'var(--ui-foreground)',
  'tabs.radius': 'var(--ui-radius)',
  'dialog.background': 'var(--ui-surface)',
  'dialog.foreground': 'var(--ui-foreground)',
  'dialog.border': 'var(--ui-border)',
  'dialog.radius': 'var(--ui-radius-lg)',
  'dialog.shadow': 'var(--ui-shadow-lg)',
  'dialog.duration-enter': 'var(--ui-duration-slow)',
  'dialog.duration-exit': 'var(--ui-duration-normal)',
  'sheet.background': 'var(--ui-surface)',
  'sheet.foreground': 'var(--ui-foreground)',
  'sheet.border': 'var(--ui-border)',
  'sheet.radius': 'var(--ui-radius-lg)',
  'sheet.shadow': 'var(--ui-shadow-lg)',
  'popover.background': 'var(--ui-surface)',
  'popover.foreground': 'var(--ui-foreground)',
  'popover.border': 'var(--ui-border)',
  'popover.radius': 'var(--ui-radius)',
  'popover.shadow': 'var(--ui-shadow)',
  'tooltip.background': 'var(--ui-inverse)',
  'tooltip.foreground': 'var(--ui-inverse-foreground)',
  'tooltip.radius': 'var(--ui-radius-sm)',
  'toast.background': 'var(--ui-inverse)',
  'toast.foreground': 'var(--ui-inverse-foreground)',
  'toast.description': 'var(--ui-inverse-muted)',
  'toast.border': 'transparent',
  'toast.radius': 'var(--ui-radius)',
  'toast.shadow': 'var(--ui-shadow)',
  'toast.action-background': 'var(--ui-inverse-foreground)',
  'toast.action-foreground': 'var(--ui-inverse)',
  'switch.background': 'var(--ui-muted)',
  'switch.checked': 'var(--ui-primary)',
  'switch.thumb': 'var(--ui-primary-foreground)',
  'switch.thumb-unchecked': 'var(--ui-foreground)',
  'switch.radius': 'var(--ui-radius)',
  'switch.thumb-radius': 'max(0px, calc(var(--ui-switch-radius) - 2px))',
  'checkbox.background': 'var(--ui-surface)',
  'checkbox.border': 'var(--ui-control-border)',
  'checkbox.checked': 'var(--ui-primary)',
  'checkbox.foreground': 'var(--ui-primary-foreground)',
  'checkbox.radius': 'var(--ui-radius-sm)',
  'radio.checked': 'var(--ui-primary)',
  'radio.background': 'var(--ui-surface)',
  'radio.border': 'var(--ui-control-border)',
  'switch.border': 'var(--ui-control-border)',
  'select.background': 'var(--ui-surface)',
  'select.foreground': 'var(--ui-foreground)',
  'select.border': 'var(--ui-control-border)',
  'select.radius': 'var(--ui-radius)',
  'select.height': 'var(--ui-control-height)',
  'select.placeholder': 'var(--ui-muted-foreground)',
  'select.focus': 'var(--ui-focus-ring)',
  'temporal.background': 'var(--ui-surface)',
  'temporal.foreground': 'var(--ui-foreground)',
  'temporal.border': 'var(--ui-control-border)',
  'temporal.radius': 'var(--ui-radius)',
  'temporal.control-height': 'var(--ui-control-height)',
  'temporal.focus': 'var(--ui-focus-ring)',
  'slider.track': 'var(--ui-muted)',
  'slider.range': 'var(--ui-primary)',
  'slider.thumb': 'var(--ui-surface)',
  'skeleton.background': 'var(--ui-surface-highest)',
  'skeleton.highlight': 'var(--ui-surface-lowest)',
  'skeleton.radius': 'var(--ui-radius)',
  'calendar.background': 'var(--ui-surface)',
  'calendar.foreground': 'var(--ui-foreground)',
  'calendar.selected': 'var(--ui-primary)',
  'calendar.selected-foreground': 'var(--ui-primary-foreground)',
  'calendar.range': 'var(--ui-primary-container)',
  'calendar.range-foreground': 'var(--ui-primary-container-foreground)',
  'calendar.hover': 'var(--ui-muted)',
  'calendar.radius': 'var(--ui-radius)',
  'calendar.day-size': '32px',
  'table.background': 'var(--ui-surface)',
  'table.foreground': 'var(--ui-foreground)',
  'table.muted-foreground': 'var(--ui-muted-foreground)',
  'table.header': 'var(--ui-surface-low)',
  'table.border': 'var(--ui-border)',
  'table.hover': 'var(--ui-muted)',
  'table.selected': 'var(--ui-primary-container)',
  'table.selected-foreground': 'var(--ui-primary-container-foreground)',
  'scrollbar.track': 'transparent',
  'scrollbar.thumb': 'var(--ui-outline)',
  'scrollbar.width': '6px',
  'chart.background': 'var(--ui-surface)',
  'chart.foreground': 'var(--ui-foreground)',
  'chart.tooltip-background': 'var(--ui-surface)',
  'chart.tooltip-foreground': 'var(--ui-foreground)',
  'chart.radius': 'var(--ui-radius)',
  'badge.background': 'var(--ui-muted)',
  'badge.foreground': 'var(--ui-foreground)',
  'badge.radius': 'var(--ui-radius-sm)',
  'alert.background': 'var(--ui-surface)',
  'alert.foreground': 'var(--ui-foreground)',
  'alert.border': 'var(--ui-border)',
  'alert.radius': 'var(--ui-radius)',
} as const;

export type PaletteFamily =
  'primary' | 'secondary' | 'tertiary' | 'neutral' | 'neutral-variant' | 'error';
export const paletteTones = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 99, 100] as const;
export type PaletteTone = (typeof paletteTones)[number];
export type ThemeToken =
  | keyof typeof lightTokens
  | keyof typeof componentTokenAliases
  | `palette.${PaletteFamily}.${PaletteTone}`;
export type ThemeTokens = Partial<Record<ThemeToken, string>>;
export const tokenNames: ThemeToken[] = /* @__PURE__ */ buildTokenNames();
function buildTokenNames(): ThemeToken[] {
  return [
    ...(Object.keys(lightTokens) as (keyof typeof lightTokens)[]),
    ...(Object.keys(componentTokenAliases) as (keyof typeof componentTokenAliases)[]),
    ...(
      ['primary', 'secondary', 'tertiary', 'neutral', 'neutral-variant', 'error'] as const
    ).flatMap((family) => paletteTones.map((tone) => `palette.${family}.${tone}` as const)),
  ];
}
export function tokenVariable(token: ThemeToken): `--ui-${string}` {
  return `--ui-${token.replaceAll('.', '-')}`;
}
export function tokensToStyle(tokens: ThemeTokens = {}) {
  return Object.fromEntries(
    Object.entries(tokens)
      .filter(([, value]) => value !== undefined)
      .map(([key, value]) => [tokenVariable(key as ThemeToken), value]),
  ) as Record<`--ui-${string}`, string>;
}
export function themeCSS(tokens: ThemeTokens, selector = ':root'): string {
  return `${selector} {\n${Object.entries(tokens)
    .filter(([, value]) => value !== undefined)
    .map(([key, value]) => `  ${tokenVariable(key as ThemeToken)}: ${value};`)
    .join('\n')}\n}\n`;
}
