import { seed, row, choices } from './shared';

export const coreBlocks = [
  seed(
    'auth-password',
    'Password sign-in',
    'Email and password access with visibility control, validation, and an account summary.',
    ['login', 'email', 'password'],
    {
      family: 'authentication',
      variant: 'password',
      brand: 'Forma',
      title: 'Welcome back',
      subtitle: 'Your workspace is ready.',
      action: 'Sign in',
    },
  ),
  seed(
    'auth-signup',
    'Account registration',
    'Create a profile with password strength, terms consent, and a completed-account state.',
    ['registration', 'consent', 'profile'],
    {
      family: 'authentication',
      variant: 'signup',
      brand: 'Forma',
      title: 'Create your account',
      subtitle: 'Make room for your next project.',
      action: 'Create account',
    },
  ),
  seed(
    'auth-magic-link',
    'Email access link',
    'Request a local access-link record, change the address, and open the generated access state.',
    ['passwordless', 'email', 'link'],
    {
      family: 'authentication',
      variant: 'magic-link',
      brand: 'Postbox',
      title: 'Continue with email',
      subtitle: 'One address. Your entire inbox.',
      action: 'Create access link',
    },
  ),
  seed(
    'auth-verification',
    'Verification checkpoint',
    'Validate a six-digit code with an explicit local code generator and retry flow.',
    ['otp', 'verification', 'security'],
    {
      family: 'authentication',
      variant: 'verification',
      brand: 'Vault',
      title: 'Verify your identity',
      subtitle: 'Enter your six-digit verification code.',
      action: 'Verify code',
    },
  ),
  seed(
    'auth-recovery',
    'Account recovery',
    'Collect a recovery address and produce a reset request that can be opened locally.',
    ['recovery', 'reset', 'email'],
    {
      family: 'authentication',
      variant: 'recovery',
      brand: 'Forma',
      title: 'Recover your account',
      subtitle: 'Start with your account email.',
      action: 'Create reset request',
    },
  ),
  seed(
    'auth-reset',
    'New password',
    'Confirm a replacement password with matching-field and length validation.',
    ['password', 'confirmation'],
    {
      family: 'authentication',
      variant: 'reset',
      brand: 'Vault',
      title: 'Choose a new password',
      subtitle: 'A fresh start for your account.',
      action: 'Update password',
    },
  ),
  seed(
    'auth-invitation',
    'Team invitation',
    'Review the inviter and role, enter your name, and accept or decline team membership.',
    ['teams', 'invitation', 'membership'],
    {
      family: 'authentication',
      variant: 'invitation',
      brand: 'Northstar Studio',
      title: 'Join Northstar Studio',
      subtitle: 'Avery invited you as a designer.',
      action: 'Accept invitation',
      choices: choices('Designer', 'Developer', 'Project manager'),
    },
  ),
  seed(
    'auth-workspace',
    'Organization access',
    'Choose a workspace and team role before entering an organization-specific account view.',
    ['organization', 'workspace', 'role'],
    {
      family: 'authentication',
      variant: 'workspace',
      brand: 'Orbit',
      title: 'Choose your workspace',
      subtitle: 'Continue to the team you are working with.',
      action: 'Open workspace',
      choices: choices('Orbit Product', 'Orbit Research', 'Personal workspace'),
    },
  ),
  seed(
    'auth-unlock',
    'Session unlock',
    'Unlock a named account with a local PIN, or switch to an email sign-in flow.',
    ['session', 'pin', 'lock'],
    {
      family: 'authentication',
      variant: 'unlock',
      brand: 'Fieldwork',
      title: 'Welcome back, Avery',
      subtitle: 'Your session is locked.',
      action: 'Unlock session',
    },
  ),
  seed(
    'auth-device',
    'Device pairing',
    'Generate a local pairing code, approve the named device, and revoke the resulting pairing.',
    ['device', 'pairing', 'approval'],
    {
      family: 'authentication',
      variant: 'device',
      brand: 'Relay',
      title: 'Connect this device',
      subtitle: 'Relay Desktop · Windows',
      action: 'Approve device',
    },
  ),

  seed(
    'nav-sidebar',
    'Project sidebar',
    'Collapsible project navigation with counts, workspace context, and matching content panels.',
    ['sidebar', 'projects', 'collapse'],
    {
      family: 'navigation',
      variant: 'sidebar',
      title: 'Northstar',
      subtitle: 'Product workspace',
      items: [
        row('projects', 'Projects', 'Three projects are active.', 'Active', 3),
        row('tasks', 'My tasks', 'Design review, token audit, release notes.', undefined, 12),
        row('activity', 'Activity', 'Avery published the new navigation.', undefined, 8),
        row('archive', 'Archive', 'Completed and archived projects.', undefined, 4),
      ],
    },
  ),
  seed(
    'nav-topbar',
    'Commerce top navigation',
    'A compact store header with section navigation, searchable collections, and a cart drawer.',
    ['header', 'store', 'cart'],
    {
      family: 'navigation',
      variant: 'topbar',
      title: 'Object',
      subtitle: 'Goods for everyday use',
      items: [
        row('new', 'New arrivals', 'Desk tools and small essentials.', undefined, 18),
        row('home', 'Home', 'Well-made objects for your space.', undefined, 24),
        row('work', 'Work', 'Tools that make work a little better.', undefined, 12),
        row('saved', 'Saved', 'Your shortlisted products.', undefined, 3),
      ],
    },
  ),
  seed(
    'nav-command',
    'Command search',
    'Keyboard-accessible command palette with searchable actions, recent destinations, and selected results.',
    ['command', 'search', 'palette'],
    {
      family: 'navigation',
      variant: 'command',
      title: 'Go anywhere',
      subtitle: 'Workspace commands',
      items: [
        row('create', 'Create project', 'Start a project in the current workspace.'),
        row('invite', 'Invite teammate', 'Add a person to your team.'),
        row('invoices', 'Find invoice', 'Open the billing workspace.'),
        row('settings', 'Workspace settings', 'Manage preferences and members.'),
        row('activity', 'View activity', 'See the latest workspace changes.'),
      ],
    },
  ),
  seed(
    'nav-breadcrumb',
    'Document breadcrumbs',
    'A clickable document hierarchy with sibling selection, parent navigation, and path copying.',
    ['breadcrumbs', 'documents', 'hierarchy'],
    {
      family: 'navigation',
      variant: 'breadcrumb',
      title: 'Product handbook',
      items: [
        row('workspace', 'Workspace', 'Workspace home and shared documents.'),
        row('handbook', 'Handbook', 'Product principles and team practices.'),
        row('research', 'Research', 'Interviews, findings, and synthesis.'),
        row('interviews', 'Interview guide', 'Questions for the October research round.'),
      ],
    },
  ),
  seed(
    'nav-tabs',
    'Issue workspace tabs',
    'Issue triage tabs with scoped record counts and a dedicated search field.',
    ['tabs', 'issues', 'triage'],
    {
      family: 'navigation',
      variant: 'tabs',
      title: 'Issues',
      items: [
        row(
          'assigned',
          'Assigned',
          'Keyboard focus audit, filter regression, onboarding copy.',
          undefined,
          3,
        ),
        row('created', 'Created', 'Track the issues you reported.', undefined, 5),
        row('review', 'In review', 'Awaiting review from the product team.', undefined, 2),
        row('done', 'Done', 'Completed issues from this cycle.', undefined, 18),
      ],
    },
  ),
  seed(
    'nav-rail',
    'Tool rail',
    'An accessible icon rail that changes the active editor surface and displays contextual tools.',
    ['rail', 'editor', 'tools'],
    {
      family: 'navigation',
      variant: 'rail',
      title: 'Canvas',
      items: [
        row('layers', 'Layers', 'Frame 01, Header, Product gallery.'),
        row('assets', 'Assets', 'Buttons, icons, and product photography.'),
        row('inspect', 'Inspect', 'Width 1024px · Auto layout · Gap 16px.'),
        row('history', 'History', 'Four saved versions are available.'),
      ],
    },
  ),
  seed(
    'nav-tree',
    'Folder explorer',
    'Expandable document groups, file search, and selection with a visible file detail pane.',
    ['tree', 'files', 'explorer'],
    {
      family: 'navigation',
      variant: 'tree',
      title: 'Design files',
      items: [
        row('identity', 'Identity', 'Brand guidelines.pdf'),
        row('interface', 'Interface', 'Components.fig'),
        row('research', 'Research', 'Interview notes.md'),
        row('handoff', 'Handoff', 'Release checklist.md'),
      ],
    },
  ),
  seed(
    'nav-workspace',
    'Workspace switcher',
    'Select, search, and create workspaces with plan labels and member counts.',
    ['switcher', 'organization', 'create'],
    {
      family: 'navigation',
      variant: 'workspace',
      title: 'Your workspaces',
      items: [
        row('studio', 'Northstar Studio', 'Product design', 'Pro', 12),
        row('lab', 'Research Lab', 'Discovery and experiments', 'Team', 8),
        row('personal', 'Personal', 'Private projects', 'Free', 1),
      ],
    },
  ),
  seed(
    'nav-pagination',
    'Results navigation',
    'Paginated resource results with page-size control and a working range summary.',
    ['pagination', 'resources', 'page-size'],
    {
      family: 'navigation',
      variant: 'pagination',
      title: 'Resource library',
      items: [
        row('1', 'Design principles', 'Product · 8 min read'),
        row('2', 'Accessibility checklist', 'Engineering · 12 min read'),
        row('3', 'Writing guidelines', 'Content · 6 min read'),
        row('4', 'Research playbook', 'Research · 15 min read'),
        row('5', 'Component inventory', 'Design · 10 min read'),
        row('6', 'Release process', 'Operations · 5 min read'),
        row('7', 'Onboarding guide', 'People · 7 min read'),
        row('8', 'API conventions', 'Engineering · 9 min read'),
      ],
    },
  ),
  seed(
    'nav-bottom',
    'Mobile destinations',
    'A stable bottom tab bar with destination-specific content and notification badges.',
    ['mobile', 'bottom-bar', 'destinations'],
    {
      family: 'navigation',
      variant: 'bottom',
      title: 'Daylight',
      items: [
        row('today', 'Today', 'Morning walk, read 20 pages, check in.', undefined, 3),
        row('discover', 'Discover', 'Explore nearby walks and new routines.', undefined, 8),
        row('saved', 'Saved', 'Riverside route and weekend reading list.', undefined, 4),
        row('profile', 'Profile', 'Avery Morgan · Member since August.'),
      ],
    },
  ),

  seed(
    'overview-metrics',
    'Sales snapshot',
    'Period-aware revenue, orders, and conversion totals with a daily sales breakdown.',
    ['metrics', 'sales', 'period'],
    {
      family: 'overview',
      variant: 'metrics',
      title: 'Sales overview',
      subtitle: 'October 2026',
      items: [
        row('revenue', 'Revenue', '+12.8% over last period', undefined, 28460),
        row('orders', 'Orders', '+8.2% over last period', undefined, 342),
        row('conversion', 'Conversion', '+0.4 percentage points', undefined, 3.8),
        row('average', 'Average order', '+4.2% over last period', undefined, 83.22),
      ],
    },
  ),
  seed(
    'overview-health',
    'Service health',
    'Live-shaped service status with expandable incidents and an acknowledge action.',
    ['status', 'services', 'incidents'],
    {
      family: 'overview',
      variant: 'health',
      title: 'System health',
      subtitle: 'Production · US East',
      items: [
        row('api', 'Public API', 'p95 latency 142ms · 99.98% uptime', 'Healthy', 99.98),
        row('jobs', 'Background jobs', 'Queue delay 4m · 2 jobs retrying', 'Degraded', 94.2),
        row('storage', 'Object storage', 'All regions operational', 'Healthy', 100),
        row('mail', 'Email delivery', 'Delivery rate 99.4%', 'Healthy', 99.4),
      ],
    },
  ),
  seed(
    'overview-checklist',
    'Launch checklist',
    'Track launch readiness, complete milestones, and reset the checklist.',
    ['onboarding', 'checklist', 'launch'],
    {
      family: 'overview',
      variant: 'checklist',
      title: 'Launch readiness',
      subtitle: 'Autumn collection',
      items: [
        row('photos', 'Approve product photos', '24 images · Studio team', 'Complete'),
        row('pricing', 'Confirm pricing', '12 SKUs · Finance team', 'Complete'),
        row('shipping', 'Set shipping zones', 'UK, EU, North America', 'Pending'),
        row('email', 'Schedule launch email', 'October 8 · 09:00', 'Pending'),
        row('qa', 'Complete checkout review', 'Mobile and desktop', 'Pending'),
      ],
    },
  ),
  seed(
    'overview-activity',
    'Release activity',
    'A filterable chronological release feed with unread tracking and actor context.',
    ['activity', 'feed', 'releases'],
    {
      family: 'overview',
      variant: 'activity',
      title: 'Release activity',
      subtitle: 'Interface 0.2',
      items: [
        row(
          '1',
          'Avery published navigation',
          'Merged pull request #142',
          'Design',
          undefined,
          'Avery',
          '09:42',
        ),
        row(
          '2',
          'Sam completed keyboard review',
          'All 18 focus states passed',
          'Review',
          undefined,
          'Sam',
          '09:18',
        ),
        row(
          '3',
          'Jordan updated changelog',
          'Added migration notes',
          'Content',
          undefined,
          'Jordan',
          '08:50',
        ),
        row(
          '4',
          'Mina opened a filter issue',
          'Table selection needs a reset',
          'Engineering',
          undefined,
          'Mina',
          '08:32',
        ),
      ],
    },
  ),
  seed(
    'overview-goals',
    'Quarterly objectives',
    'Adjust progress toward multiple measurable objectives and compare their targets.',
    ['goals', 'okr', 'progress'],
    {
      family: 'overview',
      variant: 'goals',
      title: 'Q4 objectives',
      subtitle: 'Product team',
      items: [
        row('retention', 'Increase 30-day retention', 'Target 72%', 'On track', 64),
        row('onboarding', 'Reduce onboarding time', 'Target 4 minutes', 'At risk', 45),
        row('quality', 'Resolve accessibility issues', 'Target 100% coverage', 'On track', 82),
      ],
    },
  ),
  seed(
    'overview-tasks',
    'Personal task queue',
    'Add, prioritize, filter, and complete assigned work in a compact daily queue.',
    ['tasks', 'priority', 'create'],
    {
      family: 'overview',
      variant: 'tasks',
      title: 'My day',
      subtitle: 'Thursday, October 1',
      items: [
        row('focus', 'Review navigation proposal', 'Project Atlas', 'High', undefined, 'Avery'),
        row('copy', 'Write empty state copy', 'Inbox redesign', 'Normal', undefined, 'Avery'),
        row('tokens', 'Audit semantic tokens', 'Design system', 'Normal', undefined, 'Avery'),
        row('notes', 'Share research notes', 'Discovery', 'Low', undefined, 'Avery'),
      ],
    },
  ),
  seed(
    'overview-files',
    'Recent documents',
    'Search and switch list/grid views, favorite documents, and open readable content.',
    ['files', 'documents', 'favorites'],
    {
      family: 'overview',
      variant: 'files',
      title: 'Recent documents',
      items: [
        row('brief', 'Product brief', 'Updated 2h ago · 12 pages', 'Document', 12, 'Avery'),
        row('notes', 'Research synthesis', 'Updated 4h ago · 8 pages', 'Document', 8, 'Mina'),
        row(
          'spec',
          'API specification',
          'Updated yesterday · 24 pages',
          'Specification',
          24,
          'Sam',
        ),
        row('retro', 'Sprint retrospective', 'Updated yesterday · 3 pages', 'Notes', 3, 'Jordan'),
      ],
    },
  ),
  seed(
    'overview-usage',
    'Workspace usage',
    'Compare resource usage with plan limits and change the selected plan to update headroom.',
    ['usage', 'limits', 'plans'],
    {
      family: 'overview',
      variant: 'usage',
      title: 'Workspace usage',
      subtitle: 'Resets October 31',
      items: [
        row('storage', 'Storage', '6.4 GB of 10 GB', undefined, 64),
        row('members', 'Members', '8 of 12 seats', undefined, 67),
        row('automations', 'Automations', '420 of 1,000 runs', undefined, 42),
        row('exports', 'Exports', '12 of 50 exports', undefined, 24),
      ],
    },
  ),
  seed(
    'overview-announcements',
    'Team bulletin',
    'Open bulletins, filter by audience, and dismiss read announcements.',
    ['announcements', 'team', 'read'],
    {
      family: 'overview',
      variant: 'announcements',
      title: 'Team bulletin',
      items: [
        row(
          'release',
          'Autumn release is ready',
          'The 0.2 release is available for review. Migration notes and the component inventory are attached.',
          'Everyone',
          undefined,
          'Sam',
          'Oct 1',
        ),
        row(
          'research',
          'Research round starts Monday',
          'Six customer interviews are scheduled. Add questions to the discussion guide before Friday.',
          'Product',
          undefined,
          'Mina',
          'Sep 30',
        ),
        row(
          'office',
          'Studio open day',
          'Join the team on October 12 for shared work and a project review.',
          'Studio',
          undefined,
          'Avery',
          'Sep 29',
        ),
      ],
    },
  ),
  seed(
    'overview-risks',
    'Project risk register',
    'Score, filter, and mitigate delivery risks with a visible severity summary.',
    ['risks', 'delivery', 'mitigation'],
    {
      family: 'overview',
      variant: 'risks',
      title: 'Delivery risks',
      subtitle: 'Project Meridian',
      items: [
        row(
          'supplier',
          'Supplier lead time',
          'Confirm backup supplier by October 5.',
          'Critical',
          90,
          'Jordan',
        ),
        row('scope', 'Checkout scope', 'Lock tax integration requirements.', 'High', 65, 'Sam'),
        row(
          'coverage',
          'Review capacity',
          'Reserve two accessibility review slots.',
          'Medium',
          40,
          'Avery',
        ),
        row(
          'copy',
          'Content approvals',
          'Assign an owner to the returns policy.',
          'Low',
          20,
          'Mina',
        ),
      ],
    },
  ),
];
