import { seed, row, choices, field } from './shared';

export const dataBlocks = [
  seed(
    'charts-revenue',
    'Revenue trend',
    'Compare revenue and operating costs with a period selector and series visibility.',
    ['area', 'revenue', 'comparison'],
    {
      family: 'charts',
      variant: 'area',
      title: 'Revenue & costs',
      primaryLabel: 'Revenue',
      secondaryLabel: 'Costs',
      unit: 'USD',
      series: [
        { name: 'Apr', primary: 18400, secondary: 11200 },
        { name: 'May', primary: 21300, secondary: 12600 },
        { name: 'Jun', primary: 19800, secondary: 11900 },
        { name: 'Jul', primary: 24100, secondary: 13200 },
        { name: 'Aug', primary: 26900, secondary: 15100 },
        { name: 'Sep', primary: 28460, secondary: 14600 },
      ],
    },
  ),
  seed(
    'charts-channels',
    'Acquisition channels',
    'Grouped bars comparing current and previous signups across acquisition sources.',
    ['bar', 'acquisition', 'marketing'],
    {
      family: 'charts',
      variant: 'bar',
      title: 'Acquisition channels',
      primaryLabel: 'This month',
      secondaryLabel: 'Last month',
      unit: 'signups',
      series: [
        { name: 'Organic', primary: 428, secondary: 380 },
        { name: 'Referral', primary: 236, secondary: 190 },
        { name: 'Paid', primary: 184, secondary: 220 },
        { name: 'Direct', primary: 142, secondary: 110 },
        { name: 'Social', primary: 92, secondary: 64 },
      ],
    },
  ),
  seed(
    'charts-latency',
    'API latency',
    'A two-series line chart with percentile context and an inspectable data table.',
    ['line', 'latency', 'monitoring'],
    {
      family: 'charts',
      variant: 'line',
      title: 'API response time',
      primaryLabel: 'p95',
      secondaryLabel: 'p50',
      unit: 'ms',
      series: [
        { name: '08:00', primary: 142, secondary: 62 },
        { name: '09:00', primary: 168, secondary: 70 },
        { name: '10:00', primary: 221, secondary: 92 },
        { name: '11:00', primary: 174, secondary: 74 },
        { name: '12:00', primary: 149, secondary: 65 },
        { name: '13:00', primary: 132, secondary: 58 },
      ],
    },
  ),
  seed(
    'charts-allocation',
    'Portfolio allocation',
    'A donut allocation with category totals, selectable legend entries, and CSV export.',
    ['donut', 'portfolio', 'allocation'],
    {
      family: 'charts',
      variant: 'donut',
      title: 'Portfolio allocation',
      primaryLabel: 'Allocation',
      unit: 'USD',
      series: [
        { name: 'Equities', primary: 42000 },
        { name: 'Bonds', primary: 24000 },
        { name: 'Cash', primary: 12000 },
        { name: 'Property', primary: 18000 },
        { name: 'Other', primary: 4000 },
      ],
    },
  ),
  seed(
    'charts-capacity',
    'Team capacity',
    'Stacked planned and available hours by team member with selectable series.',
    ['stacked', 'capacity', 'planning'],
    {
      family: 'charts',
      variant: 'stacked',
      title: 'Weekly capacity',
      primaryLabel: 'Planned',
      secondaryLabel: 'Available',
      unit: 'hours',
      series: [
        { name: 'Avery', primary: 28, secondary: 12 },
        { name: 'Sam', primary: 34, secondary: 6 },
        { name: 'Mina', primary: 22, secondary: 18 },
        { name: 'Jordan', primary: 30, secondary: 10 },
        { name: 'Riley', primary: 18, secondary: 22 },
      ],
    },
  ),
  seed(
    'charts-regions',
    'Regional fulfillment',
    'Horizontal bars comparing dispatched and returned orders by market.',
    ['horizontal', 'logistics', 'regions'],
    {
      family: 'charts',
      variant: 'horizontal',
      title: 'Regional fulfillment',
      primaryLabel: 'Dispatched',
      secondaryLabel: 'Returned',
      unit: 'orders',
      series: [
        { name: 'United Kingdom', primary: 328, secondary: 12 },
        { name: 'Germany', primary: 246, secondary: 8 },
        { name: 'France', primary: 192, secondary: 14 },
        { name: 'Netherlands', primary: 168, secondary: 6 },
        { name: 'United States', primary: 284, secondary: 18 },
      ],
    },
  ),
  seed(
    'charts-demand',
    'Demand and stock',
    'A composed bar and line view comparing sold units against available inventory.',
    ['composed', 'inventory', 'demand'],
    {
      family: 'charts',
      variant: 'composed',
      title: 'Demand & stock',
      primaryLabel: 'Units sold',
      secondaryLabel: 'In stock',
      unit: 'units',
      series: [
        { name: 'Notebook', primary: 84, secondary: 120 },
        { name: 'Desk lamp', primary: 36, secondary: 48 },
        { name: 'Headphones', primary: 62, secondary: 80 },
        { name: 'Chair', primary: 28, secondary: 32 },
        { name: 'Watch', primary: 48, secondary: 64 },
      ],
    },
  ),
  seed(
    'charts-scorecard',
    'Quality scorecard',
    'Radar comparison across reliability, accessibility, speed, and maintainability.',
    ['radar', 'quality', 'scorecard'],
    {
      family: 'charts',
      variant: 'radar',
      title: 'Release quality',
      primaryLabel: 'Release 0.2',
      secondaryLabel: 'Release 0.1',
      unit: 'score',
      series: [
        { name: 'Reliability', primary: 92, secondary: 84 },
        { name: 'Accessibility', primary: 96, secondary: 78 },
        { name: 'Performance', primary: 88, secondary: 82 },
        { name: 'Coverage', primary: 86, secondary: 72 },
        { name: 'Usability', primary: 94, secondary: 80 },
        { name: 'Maintenance', primary: 90, secondary: 74 },
      ],
    },
  ),
  seed(
    'charts-retention',
    'Engagement correlation',
    'Scatter exploration of sessions versus retention with hover values and raw-data access.',
    ['scatter', 'engagement', 'retention'],
    {
      family: 'charts',
      variant: 'scatter',
      title: 'Sessions & retention',
      primaryLabel: 'Weekly sessions',
      secondaryLabel: 'Retention %',
      series: [
        { name: 'Cohort A', primary: 2, secondary: 24 },
        { name: 'Cohort B', primary: 4, secondary: 42 },
        { name: 'Cohort C', primary: 7, secondary: 68 },
        { name: 'Cohort D', primary: 3, secondary: 36 },
        { name: 'Cohort E', primary: 9, secondary: 82 },
        { name: 'Cohort F', primary: 6, secondary: 60 },
      ],
    },
  ),
  seed(
    'charts-funnel',
    'Checkout funnel',
    'An ordered conversion funnel with stage selection and explicit loss between steps.',
    ['funnel', 'checkout', 'conversion'],
    {
      family: 'charts',
      variant: 'funnel',
      title: 'Checkout conversion',
      primaryLabel: 'Visitors',
      unit: 'people',
      series: [
        { name: 'Product viewed', primary: 8400 },
        { name: 'Added to cart', primary: 3200 },
        { name: 'Checkout started', primary: 1800 },
        { name: 'Payment entered', primary: 1280 },
        { name: 'Order placed', primary: 1040 },
      ],
    },
  ),

  seed(
    'forms-contact',
    'Customer inquiry',
    'A validated contact request with topic selection and a submitted-request summary.',
    ['contact', 'validation', 'support'],
    {
      family: 'forms',
      variant: 'stacked',
      title: 'Contact the team',
      fields: [
        field('name', 'Your name', 'text', { required: true }),
        field('email', 'Email', 'email', { required: true }),
        field('topic', 'Topic', 'select', {
          required: true,
          options: choices('Product question', 'Order support', 'Partnership'),
        }),
        field('message', 'Message', 'textarea', { required: true }),
      ],
      action: 'Create inquiry',
    },
  ),
  seed(
    'forms-project',
    'Project brief',
    'A two-section brief covering ownership, timeline, and deliverables.',
    ['brief', 'project', 'sections'],
    {
      family: 'forms',
      variant: 'sections',
      title: 'New project',
      fields: [
        field('name', 'Project name', 'text', { required: true, group: 'Project details' }),
        field('summary', 'Summary', 'textarea', { required: true, group: 'Project details' }),
        field('owner', 'Owner', 'select', {
          required: true,
          options: choices('Avery Morgan', 'Sam Chen', 'Mina Patel'),
          group: 'Ownership & timeline',
        }),
        field('date', 'Target date', 'date', { required: true, group: 'Ownership & timeline' }),
        field('budget', 'Budget (USD)', 'number', { min: 0, group: 'Ownership & timeline' }),
      ],
      action: 'Create project',
    },
  ),
  seed(
    'forms-onboarding',
    'Team setup wizard',
    'A three-step setup flow validating the current step before advancing.',
    ['wizard', 'onboarding', 'steps'],
    {
      family: 'forms',
      variant: 'wizard',
      title: 'Set up your team',
      fields: [
        field('team', 'Team name', 'text', { required: true, group: 'Team' }),
        field('size', 'Team size', 'select', {
          required: true,
          options: choices('1–5 people', '6–20 people', '21–100 people'),
          group: 'Team',
        }),
        field('goal', 'Primary goal', 'select', {
          required: true,
          options: choices('Manage projects', 'Track support', 'Share knowledge'),
          group: 'Purpose',
        }),
        field('workflow', 'Current workflow', 'textarea', { group: 'Purpose' }),
        field('email', 'Work email', 'email', { required: true, group: 'Account' }),
        field('consent', 'I agree to the workspace terms', 'checkbox', {
          required: true,
          group: 'Account',
        }),
      ],
      action: 'Finish setup',
    },
  ),
  seed(
    'forms-job',
    'Job application',
    'Candidate information beside a role summary, including resume attachment selection.',
    ['recruiting', 'application', 'attachment'],
    {
      family: 'forms',
      variant: 'split',
      title: 'Product designer',
      subtitle: 'Design · Remote · Full-time',
      fields: [
        field('name', 'Full name', 'text', { required: true }),
        field('email', 'Email', 'email', { required: true }),
        field('portfolio', 'Portfolio URL', 'text', { required: true, placeholder: 'https://' }),
        field('resume', 'Resume', 'file', { required: true }),
        field('note', 'A few words about you', 'textarea'),
      ],
      action: 'Submit application',
    },
  ),
  seed(
    'forms-newsletter',
    'Publication subscription',
    'A compact inline email form with interest selection and editable subscription state.',
    ['newsletter', 'inline', 'email'],
    {
      family: 'forms',
      variant: 'inline',
      title: 'The Field Notes',
      subtitle: 'Design, objects, and the people behind them.',
      fields: [
        field('email', 'Email address', 'email', {
          required: true,
          placeholder: 'you@example.com',
        }),
        field('interest', 'Edition', 'select', {
          initial: 'Weekly digest',
          options: choices('Weekly digest', 'Monthly journal', 'Product releases'),
        }),
      ],
      action: 'Subscribe',
    },
  ),
  seed(
    'forms-feedback',
    'Experience survey',
    'A short survey with a bounded satisfaction rating and follow-up consent.',
    ['survey', 'rating', 'feedback'],
    {
      family: 'forms',
      variant: 'survey',
      title: 'How was your visit?',
      fields: [
        field('rating', 'Satisfaction (1–5)', 'number', { required: true, min: 1, max: 5 }),
        field('reason', 'What worked well?', 'textarea'),
        field('improve', 'What could be better?', 'textarea'),
        field('followup', 'You may contact me about this feedback', 'checkbox'),
        field('email', 'Contact email', 'email'),
      ],
      action: 'Submit feedback',
    },
  ),
  seed(
    'forms-upload',
    'Asset intake',
    'Attach an asset, classify its usage, and produce an inspectable upload manifest.',
    ['upload', 'assets', 'manifest'],
    {
      family: 'forms',
      variant: 'upload',
      title: 'Add an asset',
      subtitle: 'Design library',
      fields: [
        field('file', 'Asset file', 'file', { required: true }),
        field('name', 'Display name', 'text', { required: true }),
        field('type', 'Usage', 'select', {
          required: true,
          options: choices('Product photography', 'Brand identity', 'Reference material'),
        }),
        field('alt', 'Alternative text', 'textarea', { required: true }),
        field('rights', 'I have permission to use this asset', 'checkbox', { required: true }),
      ],
      action: 'Add to library',
    },
  ),
  seed(
    'forms-article',
    'Article editor',
    'A title and body editor with word counts, category selection, and draft saving.',
    ['editor', 'publishing', 'draft'],
    {
      family: 'forms',
      variant: 'editor',
      title: 'Write a story',
      fields: [
        field('title', 'Title', 'text', {
          required: true,
          placeholder: 'A clear, thoughtful title',
        }),
        field('category', 'Section', 'select', {
          initial: 'Design',
          options: choices('Design', 'Culture', 'Objects', 'Interviews'),
        }),
        field('body', 'Story', 'textarea', { required: true }),
        field('excerpt', 'Excerpt', 'textarea'),
      ],
      action: 'Save draft',
    },
  ),
  seed(
    'forms-address',
    'Delivery address',
    'An address grid with recipient, postal code, country, and delivery instructions.',
    ['address', 'delivery', 'commerce'],
    {
      family: 'forms',
      variant: 'address',
      title: 'Delivery details',
      fields: [
        field('first', 'First name', 'text', { required: true }),
        field('last', 'Last name', 'text', { required: true }),
        field('street', 'Street address', 'text', { required: true }),
        field('city', 'City', 'text', { required: true }),
        field('postal', 'Postal code', 'text', { required: true }),
        field('country', 'Country', 'select', {
          required: true,
          options: choices('United Kingdom', 'Germany', 'France', 'United States', 'Egypt'),
        }),
        field('instructions', 'Delivery instructions', 'textarea'),
      ],
      action: 'Save address',
    },
  ),
  seed(
    'forms-reservation',
    'Workshop reservation',
    'Reserve a dated workshop with attendee count, session choice, and dietary requirements.',
    ['reservation', 'workshop', 'booking'],
    {
      family: 'forms',
      variant: 'reservation',
      title: 'Reserve your workshop',
      subtitle: 'Northstar Studio',
      fields: [
        field('name', 'Contact name', 'text', { required: true }),
        field('email', 'Email', 'email', { required: true }),
        field('session', 'Workshop', 'select', {
          required: true,
          options: choices(
            'Ceramics: October 10',
            'Printmaking: October 17',
            'Photography: October 24',
          ),
        }),
        field('attendees', 'Attendees', 'number', { required: true, min: 1, max: 8, initial: '1' }),
        field('requirements', 'Access or dietary requirements', 'textarea'),
      ],
      action: 'Reserve places',
    },
  ),

  seed(
    'tables-directory',
    'People directory',
    'Search staff by team, select members, edit roles, and export the filtered directory.',
    ['people', 'directory', 'roles'],
    {
      family: 'tables',
      variant: 'directory',
      title: 'People',
      action: 'Add member',
      editable: true,
      statuses: ['Active', 'Invited'],
      columns: [
        { key: 'title', label: 'Name' },
        { key: 'detail', label: 'Email' },
        { key: 'owner', label: 'Team' },
        { key: 'status', label: 'Status', format: 'status' },
      ],
      rows: [
        row('p1', 'Avery Morgan', 'avery@northstar.example', 'Active', undefined, 'Design'),
        row('p2', 'Sam Chen', 'sam@northstar.example', 'Active', undefined, 'Engineering'),
        row('p3', 'Mina Patel', 'mina@northstar.example', 'Active', undefined, 'Research'),
        row('p4', 'Jordan Lee', 'jordan@northstar.example', 'Invited', undefined, 'Operations'),
        row('p5', 'Riley Brooks', 'riley@northstar.example', 'Active', undefined, 'Design'),
        row('p6', 'Alex Rivera', 'alex@northstar.example', 'Invited', undefined, 'Engineering'),
      ],
    },
  ),
  seed(
    'tables-inventory',
    'Stock inventory',
    'SKU stock levels, restock selection, availability filtering, and editable item quantities.',
    ['inventory', 'sku', 'restock'],
    {
      family: 'tables',
      variant: 'inventory',
      title: 'Inventory',
      action: 'Add product',
      editable: true,
      statuses: ['In stock', 'Low stock', 'Out of stock'],
      columns: [
        { key: 'title', label: 'Product' },
        { key: 'detail', label: 'SKU' },
        { key: 'value', label: 'Stock', format: 'number' },
        { key: 'status', label: 'Availability', format: 'status' },
      ],
      rows: [
        row('s1', 'Studio headphones', 'OBJ-001', 'In stock', 48),
        row('s2', 'Desk lamp', 'OBJ-002', 'Low stock', 8),
        row('s3', 'Pocket notebook', 'OBJ-003', 'In stock', 124),
        row('s4', 'Task chair', 'OBJ-004', 'Out of stock', 0),
        row('s5', 'Field watch', 'OBJ-005', 'In stock', 32),
        row('s6', 'Carry bag', 'OBJ-006', 'Low stock', 6),
      ],
    },
  ),
  seed(
    'tables-invoices',
    'Accounts receivable',
    'Invoice totals, due dates, payment status, and a local mark-paid workflow.',
    ['invoices', 'receivables', 'payment'],
    {
      family: 'tables',
      variant: 'invoices',
      title: 'Invoices',
      action: 'New invoice',
      statuses: ['Paid', 'Pending', 'Overdue'],
      columns: [
        { key: 'id', label: 'Invoice' },
        { key: 'title', label: 'Customer' },
        { key: 'date', label: 'Due date' },
        { key: 'value', label: 'Amount', format: 'money' },
        { key: 'status', label: 'Status', format: 'status' },
      ],
      rows: [
        row('INV-1042', 'Forma Studio', 'Brand identity', 'Paid', 4200, undefined, '2026-09-25'),
        row('INV-1043', 'Meridian', 'Website design', 'Pending', 6800, undefined, '2026-10-05'),
        row('INV-1044', 'Daylight', 'Product research', 'Overdue', 2400, undefined, '2026-09-28'),
        row('INV-1045', 'Object', 'Photography', 'Paid', 1800, undefined, '2026-09-30'),
        row('INV-1046', 'Relay', 'Design system', 'Pending', 5600, undefined, '2026-10-12'),
        row('INV-1047', 'Fieldwork', 'Consultation', 'Pending', 1200, undefined, '2026-10-15'),
      ],
    },
  ),
  seed(
    'tables-tickets',
    'Support queue',
    'Priority-aware ticket triage with assigned agents, status filters, and resolve actions.',
    ['support', 'tickets', 'triage'],
    {
      family: 'tables',
      variant: 'tickets',
      title: 'Support tickets',
      action: 'Create ticket',
      editable: true,
      statuses: ['Open', 'In progress', 'Resolved'],
      columns: [
        { key: 'id', label: 'Ticket' },
        { key: 'title', label: 'Subject' },
        { key: 'detail', label: 'Priority' },
        { key: 'owner', label: 'Assignee' },
        { key: 'status', label: 'Status', format: 'status' },
      ],
      rows: [
        row('SUP-42', 'Checkout fails on mobile', 'High', 'Open', undefined, 'Sam'),
        row('SUP-43', 'Update delivery address', 'Normal', 'In progress', undefined, 'Jordan'),
        row('SUP-44', 'Invoice receipt request', 'Low', 'Resolved', undefined, 'Mina'),
        row('SUP-45', 'Keyboard navigation issue', 'High', 'Open', undefined, 'Avery'),
        row('SUP-46', 'Product stock question', 'Normal', 'Open', undefined, 'Riley'),
        row('SUP-47', 'Return label needed', 'Normal', 'In progress', undefined, 'Jordan'),
      ],
    },
  ),
  seed(
    'tables-audit',
    'Audit trail',
    'Immutable-looking event records with actor, timestamp, severity, and downloadable evidence.',
    ['audit', 'events', 'security'],
    {
      family: 'tables',
      variant: 'audit',
      title: 'Audit log',
      action: 'Add note',
      statuses: ['Info', 'Warning', 'Critical'],
      columns: [
        { key: 'title', label: 'Event' },
        { key: 'owner', label: 'Actor' },
        { key: 'detail', label: 'Resource' },
        { key: 'date', label: 'Time' },
        { key: 'status', label: 'Severity', format: 'status' },
      ],
      rows: [
        row('a1', 'Role changed', 'Workspace / Design', 'Info', undefined, 'Avery', '09:42'),
        row('a2', 'Access denied', 'Billing / Export', 'Warning', undefined, 'Jordan', '09:36'),
        row('a3', 'API key revoked', 'Production API', 'Critical', undefined, 'Sam', '09:24'),
        row('a4', 'Member invited', 'Workspace / Research', 'Info', undefined, 'Mina', '09:12'),
        row('a5', 'Settings updated', 'Workspace / General', 'Info', undefined, 'Avery', '08:55'),
        row('a6', 'Export completed', 'Invoice report', 'Info', undefined, 'Riley', '08:40'),
      ],
    },
  ),
  seed(
    'tables-leads',
    'Sales pipeline',
    'Deal stage, owner, and value with a local advance-stage action and deal creation.',
    ['crm', 'pipeline', 'deals'],
    {
      family: 'tables',
      variant: 'leads',
      title: 'Opportunities',
      action: 'Add deal',
      editable: true,
      statuses: ['Discovery', 'Proposal', 'Negotiation', 'Won'],
      columns: [
        { key: 'title', label: 'Company' },
        { key: 'detail', label: 'Opportunity' },
        { key: 'owner', label: 'Owner' },
        { key: 'value', label: 'Value', format: 'money' },
        { key: 'status', label: 'Stage', format: 'status' },
      ],
      rows: [
        row('l1', 'Meridian', 'Annual workspace', 'Discovery', 12000, 'Avery'),
        row('l2', 'Orbit Labs', 'Team expansion', 'Proposal', 8400, 'Sam'),
        row('l3', 'Daylight', 'Research program', 'Negotiation', 6400, 'Mina'),
        row('l4', 'Forma', 'Enterprise access', 'Won', 24000, 'Jordan'),
        row('l5', 'Fieldwork', 'Pilot program', 'Discovery', 3200, 'Riley'),
        row('l6', 'Relay', 'Annual renewal', 'Proposal', 9800, 'Avery'),
      ],
    },
  ),
  seed(
    'tables-deployments',
    'Deployment history',
    'Environment-specific build history with commit references, durations, and retry actions.',
    ['deployments', 'builds', 'engineering'],
    {
      family: 'tables',
      variant: 'deployments',
      title: 'Deployments',
      action: 'New deployment',
      statuses: ['Ready', 'Building', 'Failed'],
      columns: [
        { key: 'id', label: 'Build' },
        { key: 'title', label: 'Commit' },
        { key: 'detail', label: 'Environment' },
        { key: 'value', label: 'Seconds', format: 'number' },
        { key: 'status', label: 'State', format: 'status' },
      ],
      rows: [
        row('DEP-128', 'a8c42f1 · Update navigation', 'Production', 'Ready', 42),
        row('DEP-127', '9b2d7e4 · Add role guard', 'Preview', 'Ready', 38),
        row('DEP-126', '12cf6aa · Fix calendar', 'Production', 'Failed', 26),
        row('DEP-125', '42aa1c8 · Update tokens', 'Preview', 'Building', 18),
        row('DEP-124', 'b19e308 · Release notes', 'Production', 'Ready', 35),
        row('DEP-123', 'c924dde · Filter reset', 'Preview', 'Ready', 40),
      ],
    },
  ),
  seed(
    'tables-expenses',
    'Expense report',
    'Categorized reimbursements with merchant names, dates, amounts, and approval actions.',
    ['expenses', 'reimbursement', 'approval'],
    {
      family: 'tables',
      variant: 'expenses',
      title: 'Expense claims',
      action: 'Add expense',
      statuses: ['Pending', 'Approved', 'Declined'],
      columns: [
        { key: 'title', label: 'Merchant' },
        { key: 'detail', label: 'Category' },
        { key: 'owner', label: 'Submitted by' },
        { key: 'value', label: 'Amount', format: 'money' },
        { key: 'status', label: 'Status', format: 'status' },
      ],
      rows: [
        row('e1', 'City Rail', 'Travel', 'Pending', 48.5, 'Avery', '2026-09-30'),
        row('e2', 'Paper & Ink', 'Supplies', 'Approved', 126, 'Mina', '2026-09-29'),
        row('e3', 'Studio Kitchen', 'Meals', 'Pending', 64.8, 'Jordan', '2026-09-29'),
        row('e4', 'CloudHost', 'Software', 'Approved', 89, 'Sam', '2026-09-28'),
        row('e5', 'Central Hotel', 'Travel', 'Pending', 240, 'Riley', '2026-09-27'),
        row('e6', 'Corner Cafe', 'Meals', 'Declined', 18.4, 'Avery', '2026-09-26'),
      ],
    },
  ),
  seed(
    'tables-orders',
    'Fulfillment orders',
    'Order totals, customer names, fulfillment stages, and local dispatch actions.',
    ['orders', 'fulfillment', 'dispatch'],
    {
      family: 'tables',
      variant: 'orders',
      title: 'Orders',
      action: 'Create order',
      statuses: ['New', 'Packed', 'Dispatched', 'Delivered'],
      columns: [
        { key: 'id', label: 'Order' },
        { key: 'title', label: 'Customer' },
        { key: 'detail', label: 'Items' },
        { key: 'value', label: 'Total', format: 'money' },
        { key: 'status', label: 'Fulfillment', format: 'status' },
      ],
      rows: [
        row('ORD-842', 'Alex Rivera', 'Headphones × 1', 'New', 149),
        row('ORD-843', 'Taylor Kim', 'Notebook × 3', 'Packed', 54),
        row('ORD-844', 'Casey Park', 'Desk lamp × 1', 'Dispatched', 84),
        row('ORD-845', 'Morgan Reed', 'Watch × 1', 'Delivered', 129),
        row('ORD-846', 'Jamie Fox', 'Chair × 1', 'New', 240),
        row('ORD-847', 'Robin Cole', 'Carry bag × 2', 'Packed', 116),
      ],
    },
  ),
  seed(
    'tables-timesheets',
    'Weekly timesheets',
    'Project hours, team members, and review status with approved-hour aggregation.',
    ['timesheets', 'hours', 'review'],
    {
      family: 'tables',
      variant: 'timesheets',
      title: 'Time entries',
      action: 'Log time',
      editable: true,
      statuses: ['Draft', 'Submitted', 'Approved'],
      columns: [
        { key: 'title', label: 'Project' },
        { key: 'owner', label: 'Team member' },
        { key: 'date', label: 'Date' },
        { key: 'value', label: 'Hours', format: 'number' },
        { key: 'status', label: 'Status', format: 'status' },
      ],
      rows: [
        row('t1', 'Atlas redesign', 'Interface review', 'Submitted', 6.5, 'Avery', '2026-10-01'),
        row('t2', 'Design system', 'Component implementation', 'Approved', 7, 'Sam', '2026-10-01'),
        row('t3', 'Discovery', 'Interview synthesis', 'Draft', 4.5, 'Mina', '2026-10-01'),
        row('t4', 'Autumn launch', 'Supplier coordination', 'Submitted', 5, 'Jordan', '2026-09-30'),
        row('t5', 'Atlas redesign', 'Prototype testing', 'Approved', 6, 'Riley', '2026-09-30'),
        row('t6', 'Design system', 'Keyboard audit', 'Draft', 3.5, 'Avery', '2026-09-30'),
      ],
    },
  ),
];
