import { seed, row } from './shared';

export const personalBlocks = [
  seed(
    'finance-budget',
    'Department budget',
    'Edit budget allocations and compare actual spending against an overall budget cap.',
    ['budget', 'allocation', 'spend'],
    {
      family: 'finance',
      variant: 'budget',
      title: 'October budget',
      balance: 12000,
      items: [
        row('software', 'Software', 'Tools and subscriptions', undefined, 2400),
        row('people', 'Contractors', 'Design and engineering', undefined, 5400),
        row('travel', 'Travel', 'Visits and workshops', undefined, 1800),
        row('supplies', 'Supplies', 'Studio and materials', undefined, 800),
      ],
    },
  ),
  seed(
    'finance-expense',
    'Expense capture',
    'Record an amount, merchant, category, and receipt filename with a claim summary.',
    ['expense', 'receipt', 'capture'],
    {
      family: 'finance',
      variant: 'expense',
      title: 'New expense',
      balance: 500,
      items: [
        row('travel', 'Travel', 'Transport and accommodation'),
        row('meals', 'Meals', 'Work meals and hospitality'),
        row('supplies', 'Supplies', 'Studio materials'),
        row('software', 'Software', 'Tools and subscriptions'),
      ],
    },
  ),
  seed(
    'finance-transfer',
    'Account transfer',
    'Transfer a bounded amount between local account balances with a review confirmation.',
    ['transfer', 'accounts', 'confirmation'],
    {
      family: 'finance',
      variant: 'transfer',
      title: 'Move money',
      balance: 8400,
      items: [
        row('operating', 'Operating account', 'USD · Ending 1042', undefined, 8400),
        row('reserve', 'Reserve account', 'USD · Ending 2048', undefined, 12600),
        row('tax', 'Tax reserve', 'USD · Ending 4096', undefined, 3200),
      ],
    },
  ),
  seed(
    'finance-invoice',
    'Invoice builder',
    'Editable invoice line quantities and rates with tax calculation and downloadable line-item CSV.',
    ['invoice', 'line-items', 'tax'],
    {
      family: 'finance',
      variant: 'invoice',
      title: 'Invoice INV-1048',
      subtitle: 'Northstar Studio → Meridian',
      balance: 0,
      items: [
        row('design', 'Product design', 'Interface and interaction', undefined, 1200),
        row('research', 'User research', 'Interviews and synthesis', undefined, 800),
        row('handoff', 'Developer handoff', 'Documentation and review', undefined, 400),
      ],
    },
  ),
  seed(
    'finance-approvals',
    'Payment approvals',
    'Review pending payments, approve or decline claims, and track the approved total.',
    ['payments', 'approval', 'review'],
    {
      family: 'finance',
      variant: 'approvals',
      title: 'Payment review',
      balance: 5000,
      items: [
        row('p1', 'Studio rent', 'Due October 3', 'Pending', 1800, 'Jordan'),
        row('p2', 'Photography invoice', 'Due October 5', 'Pending', 640, 'Avery'),
        row('p3', 'Workshop supplies', 'Due October 7', 'Approved', 240, 'Mina'),
        row('p4', 'Travel reimbursement', 'Due October 8', 'Pending', 180, 'Sam'),
      ],
    },
  ),
  seed(
    'finance-transactions',
    'Account ledger',
    'Search transactions, filter incoming/outgoing entries, inspect details, and export visible records.',
    ['ledger', 'transactions', 'filter'],
    {
      family: 'finance',
      variant: 'transactions',
      title: 'Transactions',
      balance: 18420,
      items: [
        row('tx1', 'Meridian', 'Invoice INV-1040', 'Incoming', 6800, undefined, '2026-10-01'),
        row('tx2', 'Studio rent', 'October rent', 'Outgoing', -1800, undefined, '2026-10-01'),
        row('tx3', 'CloudHost', 'Monthly subscription', 'Outgoing', -89, undefined, '2026-09-30'),
        row('tx4', 'Forma', 'Invoice INV-1039', 'Incoming', 4200, undefined, '2026-09-29'),
        row('tx5', 'Paper & Ink', 'Workshop supplies', 'Outgoing', -126, undefined, '2026-09-28'),
      ],
    },
  ),
  seed(
    'finance-reconcile',
    'Bank reconciliation',
    'Match statement entries to ledger records and see the remaining unmatched balance.',
    ['reconciliation', 'matching', 'statement'],
    {
      family: 'finance',
      variant: 'reconcile',
      title: 'Reconcile September',
      balance: 10874,
      items: [
        row('r1', 'Client payment', 'Statement +6,800 · Ledger INV-1040', 'Unmatched', 6800),
        row('r2', 'Client payment', 'Statement +4,200 · Ledger INV-1039', 'Matched', 4200),
        row('r3', 'Office supplies', 'Statement -126 · Ledger EXP-428', 'Unmatched', -126),
      ],
    },
  ),
  seed(
    'finance-payout',
    'Payout scheduling',
    'Choose a payout destination, amount, and date with a balance-aware confirmation.',
    ['payout', 'destination', 'schedule'],
    {
      family: 'finance',
      variant: 'payout',
      title: 'Schedule payout',
      balance: 2840,
      items: [
        row('bank', 'Studio bank account', 'Bank transfer · Ending 1042', 'Verified'),
        row('reserve', 'Reserve account', 'Bank transfer · Ending 2048', 'Verified'),
      ],
    },
  ),
  seed(
    'finance-billing',
    'Billing statement',
    'An itemized subscription statement with seat quantity, credits, and invoice export.',
    ['billing', 'seats', 'statement'],
    {
      family: 'finance',
      variant: 'billing',
      title: 'October statement',
      subtitle: 'Workspace billing',
      balance: 24,
      items: [
        row('seats', 'Team seats', '8 seats · $24 per seat', undefined, 8),
        row('storage', 'Storage add-on', '50 GB additional storage', undefined, 12),
        row('credit', 'Account credit', 'September adjustment', undefined, -18),
      ],
    },
  ),
  seed(
    'finance-forecast',
    'Runway forecast',
    'Adjust monthly revenue and expenses to calculate projected balance and operating runway.',
    ['forecast', 'runway', 'projection'],
    {
      family: 'finance',
      variant: 'forecast',
      title: 'Cash runway',
      balance: 48000,
      items: [
        row('revenue', 'Monthly revenue', 'Recurring customer revenue', undefined, 8200),
        row('expenses', 'Monthly expenses', 'Operating costs and payroll', undefined, 12400),
        row('months', 'Projection horizon', 'Months to forecast', undefined, 6),
      ],
    },
  ),

  seed(
    'settings-profile',
    'Personal profile',
    'Edit name, email, and biography with a dirty-state save/discard workflow.',
    ['profile', 'account', 'save'],
    {
      family: 'settings',
      variant: 'profile',
      title: 'Your profile',
      items: [
        { id: 'name', label: 'Full name', detail: 'Public display name', value: 'Avery Morgan' },
        {
          id: 'email',
          label: 'Email',
          detail: 'Account contact address',
          value: 'avery@northstar.example',
        },
        {
          id: 'bio',
          label: 'Biography',
          detail: 'A few words about you',
          value: 'Designer at Northstar Studio.',
        },
      ],
    },
  ),
  seed(
    'settings-workspace',
    'Workspace preferences',
    'Configure workspace identity, timezone, and project defaults with dirty-state tracking.',
    ['workspace', 'preferences', 'timezone'],
    {
      family: 'settings',
      variant: 'workspace',
      title: 'Workspace settings',
      items: [
        {
          id: 'name',
          label: 'Workspace name',
          detail: 'Visible to all members',
          value: 'Northstar Studio',
        },
        {
          id: 'timezone',
          label: 'Timezone',
          detail: 'Used for dates and scheduling',
          value: 'Europe/London',
        },
        {
          id: 'visibility',
          label: 'Project visibility',
          detail: 'Default for new projects',
          value: 'Private',
        },
      ],
    },
  ),
  seed(
    'settings-notifications',
    'Notification matrix',
    'Separate email, push, and digest preferences with global mute and save controls.',
    ['notifications', 'channels', 'mute'],
    {
      family: 'settings',
      variant: 'notifications',
      title: 'Notifications',
      items: [
        { id: 'mentions', label: 'Mentions', detail: 'When someone mentions you', enabled: true },
        {
          id: 'assignments',
          label: 'Assignments',
          detail: 'New work assigned to you',
          enabled: true,
        },
        {
          id: 'activity',
          label: 'Project activity',
          detail: 'Updates to followed projects',
          enabled: false,
        },
        {
          id: 'digest',
          label: 'Weekly digest',
          detail: 'Your team’s weekly summary',
          enabled: true,
        },
      ],
    },
  ),
  seed(
    'settings-security',
    'Account security',
    'Manage local session records, revoke devices, and toggle a security preference.',
    ['security', 'sessions', 'revoke'],
    {
      family: 'settings',
      variant: 'security',
      title: 'Security',
      items: [
        {
          id: 'mfa',
          label: 'Verification checkpoint',
          detail: 'Require an additional code step',
          enabled: true,
        },
        {
          id: 'desktop',
          label: 'Windows · London',
          detail: 'Current session · Active now',
          enabled: true,
        },
        { id: 'phone', label: 'iPhone · London', detail: 'Last active 2 hours ago', enabled: true },
        { id: 'tablet', label: 'iPad · Cairo', detail: 'Last active September 24', enabled: true },
      ],
    },
  ),
  seed(
    'settings-billing',
    'Plan and billing',
    'Change billing interval, select a workspace plan, and update a billing contact.',
    ['billing', 'plans', 'contact'],
    {
      family: 'settings',
      variant: 'billing',
      title: 'Plan & billing',
      items: [
        { id: 'plan', label: 'Current plan', detail: '8 active seats', value: 'Team' },
        {
          id: 'email',
          label: 'Billing email',
          detail: 'Receipts and billing notices',
          value: 'billing@northstar.example',
        },
        {
          id: 'reference',
          label: 'Purchase order',
          detail: 'Optional invoice reference',
          value: 'NS-2026-04',
        },
      ],
    },
  ),
  seed(
    'settings-api',
    'API credentials',
    'Create named local placeholder credentials, reveal their non-production values, and revoke them.',
    ['api', 'credentials', 'revoke'],
    {
      family: 'settings',
      variant: 'api',
      title: 'API keys',
      items: [
        {
          id: 'dev',
          label: 'Development',
          detail: 'Created September 12 · Read-only',
          value: 'local_demo_dev_1042',
        },
        {
          id: 'preview',
          label: 'Preview builds',
          detail: 'Created September 20 · Read-only',
          value: 'local_demo_preview_2048',
        },
      ],
    },
  ),
  seed(
    'settings-integrations',
    'Connected tools',
    'Filter available integrations, connect/disconnect local records, and inspect permissions.',
    ['integrations', 'connections', 'permissions'],
    {
      family: 'settings',
      variant: 'integrations',
      title: 'Connected tools',
      items: [
        { id: 'calendar', label: 'Calendar', detail: 'Read event titles and times', enabled: true },
        {
          id: 'storage',
          label: 'Cloud storage',
          detail: 'Read selected shared folders',
          enabled: false,
        },
        { id: 'chat', label: 'Team chat', detail: 'Read selected project channels', enabled: true },
        {
          id: 'issues',
          label: 'Issue tracker',
          detail: 'Read and update linked issues',
          enabled: false,
        },
      ],
    },
  ),
  seed(
    'settings-team',
    'Workspace roles',
    'Choose role policies, adjust member access, and invite a workspace member.',
    ['team', 'roles', 'policy'],
    {
      family: 'settings',
      variant: 'team',
      title: 'Roles & access',
      items: [
        { id: 'avery', label: 'Avery Morgan', detail: 'avery@northstar.example', value: 'Owner' },
        { id: 'sam', label: 'Sam Chen', detail: 'sam@northstar.example', value: 'Admin' },
        { id: 'mina', label: 'Mina Patel', detail: 'mina@northstar.example', value: 'Member' },
        { id: 'jordan', label: 'Jordan Lee', detail: 'jordan@northstar.example', value: 'Guest' },
      ],
    },
  ),
  seed(
    'settings-appearance',
    'Display preferences',
    'Locally preview theme, density, and text-size selections in a contained sample.',
    ['appearance', 'density', 'theme'],
    {
      family: 'settings',
      variant: 'appearance',
      title: 'Display preferences',
      items: [
        { id: 'theme', label: 'Theme', detail: 'Appearance of this workspace', value: 'Light' },
        {
          id: 'density',
          label: 'Density',
          detail: 'Spacing between records',
          value: 'Comfortable',
        },
        { id: 'size', label: 'Text size', detail: 'Reading size for content', value: 'Default' },
      ],
    },
  ),
  seed(
    'settings-danger',
    'Workspace lifecycle',
    'Export a workspace manifest, archive local workspace state, and confirm deletion by name.',
    ['workspace', 'archive', 'confirmation'],
    {
      family: 'settings',
      variant: 'danger',
      title: 'Workspace lifecycle',
      items: [
        {
          id: 'workspace',
          label: 'Northstar Studio',
          detail: '12 members · 3 active projects',
          value: 'Northstar Studio',
        },
      ],
    },
  ),

  seed(
    'mobile-inbox',
    'Personal messages',
    'Search conversations, inspect threads, send a local reply, and switch inbox views.',
    ['mobile', 'inbox', 'messages'],
    {
      family: 'mobile',
      variant: 'inbox',
      title: 'Messages',
      items: [
        row(
          'avery',
          'Avery',
          'The proposal is ready for review.',
          'Unread',
          undefined,
          'AM',
          '09:42',
        ),
        row('sam', 'Sam', 'See you at the workshop.', 'Read', undefined, 'SC', '08:30'),
        row('mina', 'Mina', 'I added the interview notes.', 'Unread', undefined, 'MP', 'Yesterday'),
      ],
    },
  ),
  seed(
    'mobile-wallet',
    'Pocket wallet',
    'Inspect local balances, choose an account, and add a bounded transfer record.',
    ['mobile', 'wallet', 'balance'],
    {
      family: 'mobile',
      variant: 'wallet',
      title: 'Wallet',
      items: [
        row('everyday', 'Everyday', 'Ending 1042', 'Active', 1240),
        row('savings', 'Savings', 'Ending 2048', 'Active', 4800),
        row('tx1', 'City Rail', 'Today · Travel', 'Outgoing', -12.5),
        row('tx2', 'Corner Cafe', 'Yesterday · Meals', 'Outgoing', -8.4),
      ],
    },
  ),
  seed(
    'mobile-fitness',
    'Activity tracker',
    'Track steps, movement, and weekly activity with a working session timer.',
    ['mobile', 'fitness', 'timer'],
    {
      family: 'mobile',
      variant: 'fitness',
      title: 'Today’s activity',
      items: [
        row('steps', 'Steps', 'Goal 8,000', undefined, 6240),
        row('move', 'Movement', 'Goal 45 minutes', undefined, 32),
        row('distance', 'Distance', 'Outdoor walks', undefined, 4.8),
      ],
    },
  ),
  seed(
    'mobile-delivery',
    'Delivery progress',
    'Follow a parcel’s stages, inspect the delivery address, and update local delivery instructions.',
    ['mobile', 'delivery', 'tracking'],
    {
      family: 'mobile',
      variant: 'delivery',
      title: 'Your delivery',
      items: [
        row('confirmed', 'Order confirmed', 'October 1 · 09:42', 'Complete'),
        row('packed', 'Packed', 'Northstar warehouse', 'Complete'),
        row('transit', 'Out for delivery', 'Expected 14:00–16:00', 'Current'),
        row('arrived', 'Delivered', '18 Elm Street, London', 'Pending'),
      ],
    },
  ),
  seed(
    'mobile-player',
    'Reading queue',
    'Select a chapter, play a reading session timer, seek progress, and save items.',
    ['mobile', 'reader', 'playback'],
    {
      family: 'mobile',
      variant: 'player',
      title: 'Field Notes',
      items: [
        row('chapter1', 'Making room', 'Chapter 1 · 12 minutes', 'Ready', 720, 'Avery Morgan'),
        row('chapter2', 'Everyday objects', 'Chapter 2 · 18 minutes', 'Ready', 1080, 'Mina Patel'),
        row('chapter3', 'Working together', 'Chapter 3 · 15 minutes', 'Ready', 900, 'Sam Chen'),
      ],
    },
  ),
  seed(
    'mobile-contacts',
    'Team contacts',
    'Search contacts, inspect their details, and compose a local message.',
    ['mobile', 'contacts', 'people'],
    {
      family: 'mobile',
      variant: 'contacts',
      title: 'People',
      items: [
        row(
          'avery',
          'Avery Morgan',
          'avery@northstar.example',
          'Design',
          undefined,
          '+44 20 7946 0101',
        ),
        row(
          'sam',
          'Sam Chen',
          'sam@northstar.example',
          'Engineering',
          undefined,
          '+44 20 7946 0102',
        ),
        row(
          'mina',
          'Mina Patel',
          'mina@northstar.example',
          'Research',
          undefined,
          '+44 20 7946 0103',
        ),
        row(
          'jordan',
          'Jordan Lee',
          'jordan@northstar.example',
          'Operations',
          undefined,
          '+44 20 7946 0104',
        ),
      ],
    },
  ),
  seed(
    'mobile-checkin',
    'Visitor check-in',
    'Select a workshop reservation, enter the attendee name, and create a check-in pass.',
    ['mobile', 'check-in', 'visitor'],
    {
      family: 'mobile',
      variant: 'checkin',
      title: 'Studio check-in',
      items: [
        row('print', 'Printmaking', 'Today · 10:00 · Workshop A', 'Available', 8),
        row('ceramics', 'Ceramics', 'Today · 13:00 · Workshop B', 'Available', 6),
        row('photo', 'Photography walk', 'Today · 15:30 · Main entrance', 'Available', 12),
      ],
    },
  ),
  seed(
    'mobile-habits',
    'Daily routines',
    'Complete habits, inspect streaks, add a routine, and reset today’s progress.',
    ['mobile', 'habits', 'streaks'],
    {
      family: 'mobile',
      variant: 'habits',
      title: 'Small steps',
      items: [
        row('walk', 'Morning walk', '20 minutes outdoors', 'Pending', 8),
        row('read', 'Read a little', '20 pages', 'Complete', 12),
        row('water', 'Drink water', '6 glasses', 'Pending', 5),
        row('reflect', 'Evening reflection', 'A few words about today', 'Pending', 4),
      ],
    },
  ),
  seed(
    'mobile-tickets',
    'Event passes',
    'Select an upcoming pass, view its booking reference, and mark attendance locally.',
    ['mobile', 'passes', 'events'],
    {
      family: 'mobile',
      variant: 'tickets',
      title: 'Your passes',
      items: [
        row('NS-1042', 'Studio open day', 'October 10 · Northstar Studio', 'Upcoming', 1),
        row('NS-1048', 'Design evening', 'October 17 · Main gallery', 'Upcoming', 2),
        row('NS-1024', 'Photography walk', 'September 24 · Riverside', 'Attended', 1),
      ],
    },
  ),
  seed(
    'mobile-capture',
    'Quick capture',
    'Capture a note, task, or idea with type selection, validation, and a searchable saved list.',
    ['mobile', 'capture', 'notes'],
    {
      family: 'mobile',
      variant: 'capture',
      title: 'Capture',
      items: [
        row('n1', 'Review checkout errors', 'Check recovery after payment failure.', 'Task'),
        row('n2', 'Workshop idea', 'A session on accessible forms.', 'Idea'),
        row('n3', 'Research reminder', 'Ask about delivery expectations.', 'Note'),
      ],
    },
  ),
];
