import {
  createEvent,
  createPerson,
  createRecord,
  makeTemplate as make,
  route,
} from './template-helpers';
import { products } from './workflows';

const journalFiles = {
  family: 'overview' as const,
  variant: 'files' as const,
  title: 'The latest stories',
  items: [
    {
      id: 'objects',
      title: 'The things we keep',
      detail: 'Objects · 8 min read',
      status: 'Essay',
      owner: 'Avery Morgan',
    },
    {
      id: 'work',
      title: 'A quieter way to work',
      detail: 'Design · 6 min read',
      status: 'Essay',
      owner: 'Sam Chen',
    },
    {
      id: 'studio',
      title: 'Inside a shared studio',
      detail: 'Culture · 12 min read',
      status: 'Interview',
      owner: 'Mina Patel',
    },
    {
      id: 'notes',
      title: 'Notes from the field',
      detail: 'Research · 5 min read',
      status: 'Journal',
      owner: 'Jordan Lee',
    },
  ],
};
export const websiteTemplates = [
  make(
    'websites',
    'object-store',
    'Object Storefront',
    'A product-led shop with inspectable photography, searchable collections, configurable products, and a cart.',
    ['storefront', 'products', 'shopping'],
    {
      brand: 'Object',
      layout: 'website',
      primaryAction: 'Save a wishlist',
      createFields: createRecord,
      website: {
        heroTitle: 'Object',
        heroCopy: 'Everyday essentials, made for use.',
        image: products[0].image,
        imageAlt: 'Studio over-ear headphones',
        action: 'Shop essentials',
      },
      routes: [
        route('collection', 'Collection', 'Everyday essentials', ['commerce-catalog']),
        route('featured', 'Featured', 'Studio headphones', ['commerce-product']),
        route('bag', 'Bag', 'Your bag', ['commerce-cart', 'commerce-discount'], 'columns'),
      ],
    },
  ),
  make(
    'websites',
    'field-watch',
    'Field Watch Boutique',
    'A focused watch product site with variant selection, side-by-side shortlist, order tracking, and returns.',
    ['watch', 'product', 'boutique'],
    {
      brand: 'Field',
      layout: 'website',
      primaryAction: 'Save a watch note',
      createFields: createRecord,
      website: {
        heroTitle: 'Field watch',
        heroCopy: 'A clear dial. A dependable everyday watch.',
        image: products[1].image,
        imageAlt: 'Stainless steel field watch with an inspectable dial',
        action: 'Choose your watch',
      },
      routes: [
        route('watch', 'The watch', 'Field watch', ['commerce-product'], 'stack', {
          'commerce-product': {
            family: 'commerce',
            variant: 'product',
            title: 'Field watch',
            products: [products[1]],
          },
        }),
        route('compare', 'Compare', 'Find your fit', ['commerce-compare'], 'stack', {
          'commerce-compare': {
            family: 'commerce',
            variant: 'compare',
            title: 'Compare sizes',
            products: [
              {
                ...products[1],
                id: 'small',
                name: 'Field 38',
                detail: '38 mm · Stainless steel · Leather strap',
                options: ['Black leather', 'Brown leather'],
              },
              {
                ...products[1],
                id: 'large',
                name: 'Field 42',
                detail: '42 mm · Stainless steel · Steel bracelet',
                price: 159,
                options: ['Steel', 'Black'],
              },
            ],
          },
        }),
        route(
          'care',
          'Order & care',
          'Your watch order',
          ['commerce-order', 'commerce-returns'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'websites',
    'workshops',
    'Northstar Workshops',
    'A workshop booking website centered on actual sessions, reservations, attendee check-in, and daily schedules.',
    ['workshops', 'booking', 'studio'],
    {
      brand: 'Northstar Studio',
      layout: 'editorial',
      primaryAction: 'New visit reminder',
      createFields: createEvent,
      routes: [
        route(
          'workshops',
          'Workshops',
          'Northstar Studio',
          ['scheduling-event', 'forms-reservation'],
          'columns',
        ),
        route(
          'visit',
          'Your visit',
          'Plan your visit',
          ['scheduling-agenda', 'scheduling-rooms'],
          'columns',
        ),
        route(
          'checkin',
          'Check in',
          'Your studio pass',
          ['mobile-checkin', 'mobile-tickets'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'websites',
    'journal',
    'Field Notes Journal',
    'A publication browser with readable story details, chapter sessions, saved notes, and edition subscription.',
    ['journal', 'publication', 'reading'],
    {
      brand: 'Field Notes',
      layout: 'website',
      primaryAction: 'Save a reading note',
      createFields: createRecord,
      website: {
        heroTitle: 'Field Notes',
        heroCopy: 'A journal of design, objects, and everyday work.',
        image: products[3].image,
        imageAlt: 'Open notebook and writing materials',
        action: 'Read the latest',
      },
      routes: [
        route('journal', 'Journal', 'The latest stories', ['overview-files'], 'stack', {
          'overview-files': journalFiles,
        }),
        route(
          'read',
          'Reading room',
          'Make room for a story',
          ['mobile-player', 'mobile-capture'],
          'columns',
        ),
        route('subscribe', 'Subscribe', 'Choose your edition', ['forms-newsletter']),
      ],
    },
  ),
  make(
    'websites',
    'product-guide',
    'Object Buying Guide',
    'A product comparison website with inspectable product photos, variants, desk-set configuration, and a contact flow.',
    ['comparison', 'guide', 'products'],
    {
      brand: 'Object Guide',
      layout: 'editorial',
      primaryAction: 'Save a shortlist note',
      createFields: createRecord,
      routes: [
        route('compare', 'Compare', 'Find your everyday essentials', ['commerce-compare']),
        route(
          'desk',
          'Desk sets',
          'Build your desk set',
          ['commerce-bundle', 'commerce-product'],
          'columns',
        ),
        route('questions', 'Questions', 'Ask about an object', ['forms-contact']),
      ],
    },
  ),
  make(
    'websites',
    'consultations',
    'Forma Consultations',
    'A service booking site with date and slot selection, project brief intake, and consultation planning.',
    ['services', 'consultation', 'booking'],
    {
      brand: 'Forma',
      layout: 'editorial',
      primaryAction: 'New project inquiry',
      createFields: createRecord,
      routes: [
        route(
          'book',
          'Book',
          'Forma consultations',
          ['scheduling-booking', 'forms-project'],
          'columns',
        ),
        route(
          'plan',
          'Planning',
          'Plan a working session',
          ['scheduling-timezone', 'scheduling-availability'],
          'columns',
        ),
        route('contact', 'Contact', 'Talk with the team', ['forms-contact']),
      ],
    },
  ),
  make(
    'websites',
    'handbook',
    'Common Handbook',
    'A public knowledge browser with document hierarchy, resource pagination, readable documents, and contribution intake.',
    ['documentation', 'handbook', 'resources'],
    {
      brand: 'Common Handbook',
      layout: 'editorial',
      primaryAction: 'Propose a contribution',
      createFields: createRecord,
      routes: [
        route(
          'handbook',
          'Handbook',
          'Common Handbook',
          ['nav-breadcrumb', 'overview-files'],
          'stack',
          {
            'overview-files': {
              family: 'overview',
              variant: 'files',
              title: 'The handbook',
              items: [
                {
                  id: 'principles',
                  title: 'Design principles',
                  detail: 'Product · 8 pages',
                  status: 'Guide',
                },
                {
                  id: 'access',
                  title: 'Accessibility',
                  detail: 'Engineering · 12 pages',
                  status: 'Checklist',
                },
                {
                  id: 'writing',
                  title: 'Writing guidelines',
                  detail: 'Content · 6 pages',
                  status: 'Guide',
                },
                {
                  id: 'research',
                  title: 'Research practice',
                  detail: 'Research · 15 pages',
                  status: 'Playbook',
                },
              ],
            },
          },
        ),
        route('resources', 'Resources', 'Resource library', ['nav-pagination']),
        route('contribute', 'Contribute', 'Write a contribution', ['forms-article']),
      ],
    },
  ),
  make(
    'websites',
    'community',
    'Gather Community',
    'A community conversation site with discussions, member directory, team polls, and event registration.',
    ['community', 'discussion', 'members'],
    {
      brand: 'Gather',
      layout: 'editorial',
      primaryAction: 'Start a discussion',
      createFields: createRecord,
      routes: [
        route(
          'discussions',
          'Discussions',
          'Gather community',
          ['collaboration-thread', 'collaboration-poll'],
          'columns',
        ),
        route(
          'people',
          'People',
          'The community',
          ['mobile-contacts', 'collaboration-members'],
          'columns',
        ),
        route(
          'events',
          'Events',
          'Community workshops',
          ['scheduling-event', 'forms-reservation'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'websites',
    'event-program',
    'Northstar Open Day',
    'An event program with session selection, personal passes, attendee check-in, and access requirements.',
    ['events', 'program', 'registration'],
    {
      brand: 'Northstar Open Day',
      layout: 'topbar',
      primaryAction: 'Save an event reminder',
      createFields: createEvent,
      routes: [
        route(
          'program',
          'Program',
          'Northstar Open Day',
          ['scheduling-event', 'scheduling-agenda'],
          'columns',
          {
            'scheduling-agenda': {
              family: 'scheduling',
              variant: 'agenda',
              title: 'Saturday program',
              date: '2026-10-10',
              slots: ['10:00', '13:00', '15:30'],
              items: [
                {
                  id: 'print',
                  title: 'Printmaking',
                  detail: 'Workshop A · Materials included',
                  date: '10:00',
                  status: 'Scheduled',
                  value: 90,
                  owner: 'Avery',
                },
                {
                  id: 'clay',
                  title: 'Ceramics',
                  detail: 'Workshop B · Beginner friendly',
                  date: '13:00',
                  status: 'Scheduled',
                  value: 120,
                  owner: 'Mina',
                },
                {
                  id: 'walk',
                  title: 'Photography walk',
                  detail: 'Meet at the main entrance',
                  date: '15:30',
                  status: 'Scheduled',
                  value: 60,
                  owner: 'Jordan',
                },
              ],
            },
          },
        ),
        route(
          'passes',
          'Passes',
          'Your event passes',
          ['mobile-tickets', 'mobile-checkin'],
          'columns',
        ),
        route('reserve', 'Reserve', 'Reserve a workshop', ['forms-reservation']),
      ],
    },
  ),
  make(
    'websites',
    'membership',
    'Common Membership',
    'A membership website with explicit plan comparison, account registration, and local billing preferences.',
    ['membership', 'plans', 'account'],
    {
      brand: 'Common Workspace',
      layout: 'topbar',
      primaryAction: 'Save a plan inquiry',
      createFields: createRecord,
      routes: [
        route('plans', 'Plans', 'Common Workspace plans', ['commerce-plans']),
        route(
          'account',
          'Join',
          'Create your workspace account',
          ['auth-signup', 'auth-workspace'],
          'columns',
        ),
        route(
          'billing',
          'Billing',
          'Membership billing',
          ['settings-billing', 'finance-billing'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'websites',
    'wholesale',
    'Object Trade Portal',
    'A trade-order portal with photographic product selection, quantity-aware cart, address capture, and invoices.',
    ['wholesale', 'trade', 'orders'],
    {
      brand: 'Object Trade',
      layout: 'topbar',
      primaryAction: 'New trade inquiry',
      createFields: createPerson,
      routes: [
        route('catalog', 'Catalog', 'Object trade collection', ['commerce-catalog']),
        route(
          'order',
          'Order',
          'Build your trade order',
          ['commerce-cart', 'forms-address'],
          'columns',
        ),
        route(
          'invoices',
          'Invoices',
          'Trade invoices',
          ['tables-invoices', 'forms-contact'],
          'stack',
        ),
      ],
    },
  ),
  make(
    'websites',
    'customer-care',
    'Object Customer Care',
    'A customer care portal for order tracking, return selection, validated inquiries, and a support inbox.',
    ['support', 'returns', 'orders'],
    {
      brand: 'Object Care',
      layout: 'editorial',
      primaryAction: 'New support note',
      createFields: createRecord,
      routes: [
        route(
          'orders',
          'Your order',
          'Object customer care',
          ['commerce-order', 'mobile-delivery'],
          'columns',
        ),
        route(
          'returns',
          'Returns',
          'Create a return request',
          ['commerce-returns', 'forms-contact'],
          'columns',
        ),
        route('messages', 'Messages', 'Your support conversation', ['collaboration-inbox']),
      ],
    },
  ),
];
