import {
  checklist,
  createEvent,
  createPerson,
  createProject,
  createRecord,
  makeTemplate as make,
  metrics,
  route,
} from './template-helpers';

export const operationalTemplates = [
  make(
    'web-apps',
    'project-space',
    'Atlas Project Space',
    'Project planning with a kanban board, launch milestones, shared files, and project access.',
    ['projects', 'kanban', 'team'],
    {
      brand: 'Atlas',
      layout: 'sidebar',
      primaryAction: 'New project',
      createFields: createProject,
      routes: [
        route(
          'board',
          'Board',
          'Project workspace',
          ['collaboration-board', 'overview-goals', 'overview-checklist'],
          'wide-first',
        ),
        route(
          'files',
          'Files',
          'Project deliverables',
          ['overview-files', 'collaboration-files'],
          'columns',
        ),
        route(
          'team',
          'Team',
          'People & discussions',
          ['collaboration-members', 'collaboration-thread'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'support-desk',
    'Relay Support Desk',
    'Customer conversations, a searchable triage queue, resolution tracking, and agent access.',
    ['support', 'inbox', 'triage'],
    {
      brand: 'Relay',
      layout: 'split',
      primaryAction: 'New ticket',
      createFields: createRecord,
      routes: [
        route(
          'inbox',
          'Inbox',
          'Customer conversations',
          ['collaboration-inbox', 'overview-metrics'],
          'stack',
          {
            'overview-metrics': metrics('Queue overview', [
              ['open', 'Open tickets', 42, '12 require review'],
              ['resolved', 'Resolved today', 18, '+4 from yesterday'],
              ['response', 'First response (min)', 12, 'Target 15 minutes'],
              ['satisfaction', 'Satisfaction', 96, 'Last 30 ratings'],
            ]),
          },
        ),
        route(
          'tickets',
          'Tickets',
          'Support queue',
          ['tables-tickets', 'collaboration-comments'],
          'stack',
        ),
        route(
          'agents',
          'Agents',
          'Support team',
          ['tables-directory', 'settings-notifications'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'sales-pipeline',
    'Meridian CRM',
    'Opportunity tracking, a searchable people directory, account notes, and sales targets.',
    ['crm', 'sales', 'pipeline'],
    {
      brand: 'Meridian',
      layout: 'sidebar',
      primaryAction: 'New opportunity',
      createFields: createRecord,
      routes: [
        route(
          'pipeline',
          'Pipeline',
          'Sales pipeline',
          ['tables-leads', 'charts-channels'],
          'wide-first',
        ),
        route(
          'people',
          'Contacts',
          'Account contacts',
          ['tables-directory', 'forms-contact'],
          'columns',
        ),
        route(
          'targets',
          'Targets',
          'Quarterly targets',
          ['overview-goals', 'collaboration-notes'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'hiring',
    'Gather Hiring',
    'Candidate intake, interview scheduling, hiring checkpoints, and reviewer discussions.',
    ['recruiting', 'candidates', 'interviews'],
    {
      brand: 'Gather',
      layout: 'topbar',
      primaryAction: 'Add candidate',
      createFields: createPerson,
      routes: [
        route(
          'candidates',
          'Candidates',
          'Hiring workspace',
          ['forms-job', 'overview-checklist'],
          'columns',
          {
            'overview-checklist': checklist('Hiring checkpoints', [
              ['role', 'Approve role brief', 'Product designer · Remote'],
              ['screen', 'Review applications', '12 candidates in the current round'],
              ['interviews', 'Schedule interviews', 'Three interview stages'],
              ['offer', 'Prepare offer', 'Compensation and start date'],
            ]),
          },
        ),
        route(
          'interviews',
          'Interviews',
          'Interview calendar',
          ['scheduling-week', 'scheduling-booking'],
          'stack',
        ),
        route(
          'review',
          'Review',
          'Candidate review',
          ['collaboration-comments', 'collaboration-approval'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'learning',
    'Fieldwork Learning',
    'A chapter-based learning workspace with reading sessions, notes, peer discussion, and progress.',
    ['learning', 'reading', 'notes'],
    {
      brand: 'Fieldwork',
      layout: 'sidebar',
      primaryAction: 'Add learning goal',
      createFields: createRecord,
      routes: [
        route(
          'learn',
          'Learn',
          'Your learning path',
          ['mobile-player', 'overview-checklist'],
          'columns',
          {
            'overview-checklist': checklist('Course progress', [
              ['principles', 'Design principles', 'Read chapter 1'],
              ['objects', 'Everyday objects', 'Read chapter 2'],
              ['teams', 'Working together', 'Read chapter 3'],
              ['reflect', 'Write a reflection', 'Share what you learned'],
            ]),
          },
        ),
        route(
          'notes',
          'Notes',
          'Learning notes',
          ['mobile-capture', 'collaboration-notes'],
          'columns',
        ),
        route(
          'community',
          'Community',
          'Study group',
          ['collaboration-thread', 'collaboration-poll'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'asset-library',
    'Archive Asset Library',
    'Searchable documents and deliverables with an asset intake manifest and review workflow.',
    ['assets', 'files', 'review'],
    {
      brand: 'Archive',
      layout: 'workbench',
      primaryAction: 'New collection',
      createFields: createRecord,
      routes: [
        route(
          'library',
          'Library',
          'Shared library',
          ['overview-files', 'collaboration-files'],
          'columns',
        ),
        route('intake', 'Intake', 'Add to the archive', ['forms-upload'], 'stack'),
        route(
          'review',
          'Review',
          'Asset review',
          ['collaboration-comments', 'collaboration-approval'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'studio-booking',
    'Northstar Booking',
    'Studio consultations, workshop registration, room reservations, and daily planning.',
    ['booking', 'studio', 'calendar'],
    {
      brand: 'Northstar',
      layout: 'topbar',
      primaryAction: 'New event',
      createFields: createEvent,
      routes: [
        route(
          'agenda',
          'Agenda',
          'Studio schedule',
          ['scheduling-agenda', 'scheduling-rooms'],
          'columns',
        ),
        route(
          'book',
          'Consultations',
          'Consultation bookings',
          ['scheduling-booking', 'scheduling-availability'],
          'columns',
        ),
        route(
          'events',
          'Workshops',
          'Upcoming workshops',
          ['scheduling-event', 'forms-reservation'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'store-manager',
    'Object Store Manager',
    'Product stock, order fulfillment, sales metrics, customer requests, and promotions.',
    ['commerce', 'inventory', 'orders'],
    {
      brand: 'Object',
      layout: 'sidebar',
      primaryAction: 'New product',
      createFields: createRecord,
      routes: [
        route(
          'overview',
          'Overview',
          'Store overview',
          ['overview-metrics', 'charts-demand', 'tables-orders'],
          'wide-first',
        ),
        route(
          'inventory',
          'Inventory',
          'Product stock',
          ['tables-inventory', 'commerce-bundle'],
          'stack',
        ),
        route(
          'customers',
          'Customers',
          'Customer requests',
          ['collaboration-inbox', 'commerce-returns'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'finance-office',
    'Balance Finance',
    'Cash transactions, budgets, editable invoices, expense capture, and payment approvals.',
    ['finance', 'invoices', 'budget'],
    {
      brand: 'Balance',
      layout: 'sidebar',
      primaryAction: 'New finance record',
      createFields: createRecord,
      routes: [
        route(
          'cash',
          'Cash',
          'Cash workspace',
          ['finance-transactions', 'finance-budget'],
          'columns',
        ),
        route(
          'invoices',
          'Invoices',
          'Receivables',
          ['tables-invoices', 'finance-invoice'],
          'stack',
        ),
        route(
          'expenses',
          'Expenses',
          'Claims & approvals',
          ['finance-expense', 'finance-approvals'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'research',
    'Observe Research',
    'Research documentation, interview planning, synthesis notes, and team decisions.',
    ['research', 'interviews', 'synthesis'],
    {
      brand: 'Observe',
      layout: 'split',
      primaryAction: 'New study',
      createFields: createProject,
      routes: [
        route(
          'studies',
          'Studies',
          'Research repository',
          ['overview-files', 'collaboration-notes'],
          'columns',
        ),
        route(
          'interviews',
          'Interviews',
          'Interview planning',
          ['scheduling-booking', 'scheduling-timezone'],
          'columns',
        ),
        route(
          'decisions',
          'Decisions',
          'Findings & decisions',
          ['collaboration-poll', 'collaboration-comments'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'team-hub',
    'Common Team Hub',
    'Team announcements, assigned tasks, shared meeting notes, and workspace membership.',
    ['team', 'announcements', 'tasks'],
    {
      brand: 'Common',
      layout: 'topbar',
      primaryAction: 'New update',
      createFields: createRecord,
      routes: [
        route(
          'today',
          'Today',
          'Team home',
          ['overview-announcements', 'overview-tasks'],
          'columns',
        ),
        route(
          'meetings',
          'Meetings',
          'Meetings & notes',
          ['scheduling-agenda', 'collaboration-notes'],
          'columns',
        ),
        route(
          'people',
          'People',
          'Your team',
          ['collaboration-members', 'settings-team'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'web-apps',
    'intake',
    'Brief Intake',
    'Project requests, structured briefs, review checkpoints, and delivery milestones.',
    ['intake', 'forms', 'projects'],
    {
      brand: 'Brief',
      layout: 'sidebar',
      primaryAction: 'New request',
      createFields: createProject,
      routes: [
        route(
          'requests',
          'Requests',
          'Project intake',
          ['forms-project', 'overview-tasks'],
          'columns',
        ),
        route(
          'review',
          'Review',
          'Request review',
          ['collaboration-approval', 'collaboration-comments'],
          'columns',
        ),
        route(
          'delivery',
          'Delivery',
          'Accepted projects',
          ['scheduling-deadlines', 'collaboration-board'],
          'stack',
        ),
      ],
    },
  ),

  make(
    'desktop-apps',
    'file-explorer',
    'Archive Explorer',
    'A folder explorer and document workspace with deliverable review and asset intake.',
    ['files', 'explorer', 'desktop'],
    {
      brand: 'Archive Explorer',
      layout: 'workbench',
      primaryAction: 'New folder',
      createFields: createRecord,
      routes: [
        route('browse', 'Browse', 'Files & folders', ['nav-tree', 'overview-files'], 'columns'),
        route('shared', 'Shared', 'Shared deliverables', ['collaboration-files'], 'stack'),
        route('import', 'Import', 'Asset intake', ['forms-upload'], 'stack'),
      ],
    },
  ),
  make(
    'desktop-apps',
    'developer-console',
    'Relay Developer Console',
    'Deployment history, service latency, audit events, and API credential records.',
    ['developer', 'deployments', 'api'],
    {
      brand: 'Relay Console',
      layout: 'workbench',
      primaryAction: 'New deployment',
      createFields: createRecord,
      routes: [
        route(
          'builds',
          'Builds',
          'Build workspace',
          ['tables-deployments', 'charts-latency'],
          'stack',
        ),
        route('events', 'Events', 'Audit events', ['tables-audit', 'overview-health'], 'columns'),
        route(
          'keys',
          'Credentials',
          'API credentials',
          ['settings-api', 'settings-security'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'mail',
    'Postbox Mail',
    'A desktop conversation workspace with shared inbox, contact directory, and notification preferences.',
    ['mail', 'conversations', 'contacts'],
    {
      brand: 'Postbox',
      layout: 'split',
      primaryAction: 'New message draft',
      createFields: createRecord,
      routes: [
        route('inbox', 'Inbox', 'Conversations', ['collaboration-inbox'], 'stack'),
        route(
          'contacts',
          'Contacts',
          'Address book',
          ['tables-directory', 'mobile-contacts'],
          'columns',
        ),
        route(
          'preferences',
          'Preferences',
          'Mail preferences',
          ['settings-notifications', 'settings-profile'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'writing',
    'Field Notes Writer',
    'An article editor with drafts, document review, publication subscription, and editorial notes.',
    ['writing', 'publishing', 'editor'],
    {
      brand: 'Field Notes',
      layout: 'workbench',
      primaryAction: 'New draft',
      createFields: createRecord,
      routes: [
        route(
          'write',
          'Write',
          'Editorial workspace',
          ['forms-article', 'overview-files'],
          'columns',
        ),
        route(
          'review',
          'Review',
          'Story review',
          ['collaboration-comments', 'collaboration-notes'],
          'columns',
        ),
        route(
          'publication',
          'Publication',
          'Publication settings',
          ['forms-newsletter', 'settings-workspace'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'bookkeeper',
    'Balance Bookkeeper',
    'Invoice preparation beside account transactions, statement matching, and cash projections.',
    ['bookkeeping', 'invoices', 'reconciliation'],
    {
      brand: 'Balance Desktop',
      layout: 'split',
      primaryAction: 'New entry',
      createFields: createRecord,
      routes: [
        route(
          'invoice',
          'Invoice',
          'Invoice workspace',
          ['finance-invoice', 'tables-invoices'],
          'stack',
        ),
        route(
          'reconcile',
          'Reconcile',
          'Statement matching',
          ['finance-reconcile', 'finance-transactions'],
          'columns',
        ),
        route(
          'forecast',
          'Forecast',
          'Cash projections',
          ['finance-forecast', 'finance-budget'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'planner',
    'Atlas Planner',
    'A desktop planning board with capacity, milestones, time entries, and meeting notes.',
    ['planning', 'kanban', 'capacity'],
    {
      brand: 'Atlas Planner',
      layout: 'workbench',
      primaryAction: 'New task',
      createFields: createRecord,
      routes: [
        route('board', 'Board', 'Planning board', ['collaboration-board'], 'stack'),
        route(
          'timeline',
          'Timeline',
          'Milestones & capacity',
          ['scheduling-deadlines', 'charts-capacity'],
          'columns',
        ),
        route(
          'time',
          'Time',
          'Time & notes',
          ['tables-timesheets', 'collaboration-notes'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'media',
    'Object Media Desk',
    'Product imagery intake, deliverable version review, and a searchable photographic collection.',
    ['media', 'photography', 'assets'],
    {
      brand: 'Object Media',
      layout: 'workbench',
      primaryAction: 'New collection',
      createFields: createRecord,
      routes: [
        route('collection', 'Collection', 'Product collection', ['commerce-catalog'], 'stack'),
        route(
          'versions',
          'Versions',
          'Deliverable versions',
          ['collaboration-files', 'overview-files'],
          'columns',
        ),
        route(
          'intake',
          'Intake',
          'Image intake',
          ['forms-upload', 'collaboration-comments'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'research-notebook',
    'Observe Notebook',
    'Meeting and research notes alongside document folders, review comments, and team decisions.',
    ['research', 'notes', 'notebook'],
    {
      brand: 'Observe Notebook',
      layout: 'split',
      primaryAction: 'New note',
      createFields: createRecord,
      routes: [
        route(
          'notes',
          'Notes',
          'Research notebook',
          ['collaboration-notes', 'nav-tree'],
          'columns',
        ),
        route(
          'review',
          'Review',
          'Synthesis review',
          ['collaboration-comments', 'collaboration-poll'],
          'columns',
        ),
        route(
          'interviews',
          'Interviews',
          'Interview sessions',
          ['scheduling-agenda', 'scheduling-timezone'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'operations',
    'Signal Operations',
    'An operational console with service status, latency exploration, audit logs, and shift handoffs.',
    ['operations', 'monitoring', 'incidents'],
    {
      brand: 'Signal',
      layout: 'dashboard',
      primaryAction: 'New incident record',
      createFields: createRecord,
      routes: [
        route(
          'status',
          'Status',
          'Operational status',
          ['overview-health', 'charts-latency'],
          'columns',
        ),
        route(
          'audit',
          'Audit',
          'Audit & deployments',
          ['tables-audit', 'tables-deployments'],
          'stack',
        ),
        route(
          'handoff',
          'Handoff',
          'Shift handoff',
          ['collaboration-handoff', 'scheduling-shifts'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'contacts',
    'Gather Contacts',
    'A people directory with contact detail, inquiry capture, and team access management.',
    ['contacts', 'directory', 'people'],
    {
      brand: 'Gather Contacts',
      layout: 'split',
      primaryAction: 'New contact',
      createFields: createPerson,
      routes: [
        route('directory', 'Directory', 'People directory', ['tables-directory'], 'stack'),
        route(
          'details',
          'Contact cards',
          'Contact details',
          ['mobile-contacts', 'forms-contact'],
          'columns',
        ),
        route(
          'access',
          'Access',
          'Workspace access',
          ['settings-team', 'collaboration-members'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'time',
    'Tempo Time Desk',
    'Time-entry review, daily planning, capacity comparison, and expense records.',
    ['time', 'timesheets', 'capacity'],
    {
      brand: 'Tempo',
      layout: 'topbar',
      primaryAction: 'New time entry',
      createFields: createRecord,
      routes: [
        route(
          'entries',
          'Entries',
          'Time workspace',
          ['tables-timesheets', 'charts-capacity'],
          'stack',
        ),
        route('plan', 'Plan', 'Daily plan', ['scheduling-agenda', 'overview-tasks'], 'columns'),
        route(
          'expenses',
          'Expenses',
          'Project expenses',
          ['tables-expenses', 'finance-expense'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'desktop-apps',
    'calendar',
    'Northstar Calendar',
    'Weekly and daily calendar views with availability, meeting rooms, and distributed time planning.',
    ['calendar', 'events', 'availability'],
    {
      brand: 'Northstar Calendar',
      layout: 'workbench',
      primaryAction: 'New event',
      createFields: createEvent,
      routes: [
        route('week', 'Week', 'Weekly schedule', ['scheduling-week'], 'stack'),
        route('day', 'Day', 'Daily agenda', ['scheduling-agenda', 'scheduling-rooms'], 'columns'),
        route(
          'availability',
          'Availability',
          'Working hours',
          ['scheduling-availability', 'scheduling-timezone'],
          'columns',
        ),
      ],
    },
  ),
];
