import {
  createEvent,
  createPerson,
  createRecord,
  makeTemplate as make,
  metrics,
  route,
} from './template-helpers';

export const personalTemplates = [
  make(
    'mobile-apps',
    'routines',
    'Daylight Routines',
    'Daily habit completion, timed walking sessions, and quick personal notes.',
    ['habits', 'fitness', 'daily'],
    {
      brand: 'Daylight',
      layout: 'mobile',
      primaryAction: 'New routine',
      createFields: createRecord,
      routes: [
        route('today', 'Today', 'Your daily routines', ['mobile-habits']),
        route('activity', 'Activity', 'Move a little', ['mobile-fitness']),
        route('notes', 'Notes', 'Small observations', ['mobile-capture']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'wallet',
    'Pocket Wallet',
    'Account balances, bounded local transfers, transaction inspection, and payout scheduling.',
    ['wallet', 'accounts', 'transfers'],
    {
      brand: 'Pocket',
      layout: 'mobile',
      primaryAction: 'New money note',
      createFields: createRecord,
      routes: [
        route('wallet', 'Wallet', 'Your accounts', ['mobile-wallet']),
        route('activity', 'Activity', 'Account activity', ['finance-transactions']),
        route('payout', 'Payout', 'Schedule a payout', ['finance-payout']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'messages',
    'Common Messenger',
    'Personal messages, a team discussion, and searchable contact cards.',
    ['messages', 'contacts', 'team'],
    {
      brand: 'Common',
      layout: 'mobile',
      primaryAction: 'New conversation',
      createFields: createPerson,
      routes: [
        route('inbox', 'Messages', 'Your conversations', ['mobile-inbox']),
        route('team', 'Team', 'Product discussion', ['collaboration-thread']),
        route('people', 'People', 'Team contacts', ['mobile-contacts']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'delivery',
    'Object Delivery',
    'Parcel stages, delivery instructions, order receipts, and return requests.',
    ['delivery', 'orders', 'returns'],
    {
      brand: 'Object Delivery',
      layout: 'mobile',
      primaryAction: 'New delivery note',
      createFields: createRecord,
      routes: [
        route('tracking', 'Track', 'Your delivery', ['mobile-delivery']),
        route('order', 'Order', 'Order details', ['commerce-order']),
        route('returns', 'Returns', 'Return an item', ['commerce-returns']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'reading',
    'Field Notes Reader',
    'A chapter queue with reading-session progress, saved captures, and publication subscription.',
    ['reader', 'chapters', 'notes'],
    {
      brand: 'Field Notes',
      layout: 'mobile',
      primaryAction: 'New reading note',
      createFields: createRecord,
      routes: [
        route('read', 'Read', 'Your reading queue', ['mobile-player']),
        route('notes', 'Notes', 'Reading notes', ['mobile-capture']),
        route('edition', 'Edition', 'Your subscription', ['forms-newsletter']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'event-pass',
    'Northstar Pass',
    'Upcoming event passes, studio attendee check-in, and workshop registration.',
    ['events', 'tickets', 'check-in'],
    {
      brand: 'Northstar Pass',
      layout: 'mobile',
      primaryAction: 'New event reminder',
      createFields: createEvent,
      routes: [
        route('passes', 'Passes', 'Your event passes', ['mobile-tickets']),
        route('checkin', 'Check in', 'Studio check-in', ['mobile-checkin']),
        route('discover', 'Workshops', 'Studio workshops', ['scheduling-event']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'capture',
    'Observe Capture',
    'Quick notes, tasks, and ideas with searchable captures, document review, and a personal queue.',
    ['capture', 'notes', 'tasks'],
    {
      brand: 'Observe',
      layout: 'mobile',
      primaryAction: 'New capture',
      createFields: createRecord,
      routes: [
        route('capture', 'Capture', 'A place for your thoughts', ['mobile-capture']),
        route('tasks', 'Tasks', 'Your next steps', ['overview-tasks']),
        route('files', 'Files', 'Recent documents', ['overview-files']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'team-directory',
    'Gather People',
    'Searchable team contacts, project membership, and personal profile editing.',
    ['people', 'directory', 'profile'],
    {
      brand: 'Gather',
      layout: 'mobile',
      primaryAction: 'New contact',
      createFields: createPerson,
      routes: [
        route('contacts', 'People', 'Team directory', ['mobile-contacts']),
        route('members', 'Project', 'Project access', ['collaboration-members']),
        route('profile', 'Profile', 'Your profile', ['settings-profile']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'appointments',
    'Tempo Appointments',
    'Consultation date and slot selection, daily agenda, and leave-range requests.',
    ['appointments', 'calendar', 'booking'],
    {
      brand: 'Tempo',
      layout: 'mobile',
      primaryAction: 'New appointment note',
      createFields: createEvent,
      routes: [
        route('book', 'Book', 'Find a consultation', ['scheduling-booking']),
        route('agenda', 'Agenda', 'Your schedule', ['scheduling-agenda']),
        route('leave', 'Time off', 'Request time off', ['scheduling-range']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'store',
    'Object Pocket Store',
    'A responsive photographic catalog, configurable product detail, and a quantity-aware bag.',
    ['shopping', 'products', 'cart'],
    {
      brand: 'Object',
      layout: 'mobile',
      primaryAction: 'New wishlist note',
      createFields: createRecord,
      routes: [
        route('shop', 'Shop', 'Everyday essentials', ['commerce-catalog']),
        route('product', 'Featured', 'Studio headphones', ['commerce-product']),
        route('bag', 'Bag', 'Your shopping bag', ['commerce-cart']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'expenses',
    'Balance Expenses',
    'Expense entry with receipt selection, approval status, and reimbursement records.',
    ['expenses', 'receipts', 'claims'],
    {
      brand: 'Balance',
      layout: 'mobile',
      primaryAction: 'New claim note',
      createFields: createRecord,
      routes: [
        route('capture', 'Capture', 'Record an expense', ['finance-expense']),
        route('claims', 'Claims', 'Your expense claims', ['tables-expenses']),
        route('review', 'Review', 'Approval status', ['finance-approvals']),
      ],
    },
  ),
  make(
    'mobile-apps',
    'workforce',
    'Shift Companion',
    'Staff assignment, incoming handoff acknowledgment, and individual availability.',
    ['shifts', 'handoff', 'staff'],
    {
      brand: 'Shift',
      layout: 'mobile',
      primaryAction: 'New handoff note',
      createFields: createRecord,
      routes: [
        route('roster', 'Roster', 'Today’s shifts', ['scheduling-shifts']),
        route('handoff', 'Handoff', 'Incoming shift', ['collaboration-handoff']),
        route('availability', 'Hours', 'Your availability', ['scheduling-availability']),
      ],
    },
  ),

  make(
    'dashboards',
    'sales',
    'Object Sales Dashboard',
    'Store revenue, order conversion, and fulfillment records in a sales operations layout.',
    ['sales', 'commerce', 'conversion'],
    {
      brand: 'Object Analytics',
      layout: 'dashboard',
      primaryAction: 'New sales annotation',
      createFields: createRecord,
      routes: [
        route(
          'sales',
          'Sales',
          'Sales performance',
          ['overview-metrics', 'charts-funnel', 'tables-orders'],
          'wide-first',
        ),
        route(
          'products',
          'Products',
          'Demand & inventory',
          ['charts-demand', 'tables-inventory'],
          'stack',
        ),
        route(
          'regions',
          'Regions',
          'Regional fulfillment',
          ['charts-regions', 'overview-risks'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'revenue',
    'Balance Revenue Dashboard',
    'Revenue and costs, cash forecasts, accounts receivable, and budget allocations.',
    ['revenue', 'cash', 'finance'],
    {
      brand: 'Balance Analytics',
      layout: 'dashboard',
      primaryAction: 'New financial annotation',
      createFields: createRecord,
      routes: [
        route(
          'revenue',
          'Revenue',
          'Revenue & runway',
          ['charts-revenue', 'finance-forecast'],
          'columns',
        ),
        route(
          'receivables',
          'Receivables',
          'Invoice performance',
          ['tables-invoices', 'finance-approvals'],
          'stack',
        ),
        route(
          'budget',
          'Budget',
          'Budget planning',
          ['finance-budget', 'finance-billing'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'support',
    'Relay Support Dashboard',
    'Support queue totals, a triage table, response activity, and customer conversations.',
    ['support', 'response', 'queue'],
    {
      brand: 'Relay Analytics',
      layout: 'dashboard',
      primaryAction: 'New queue annotation',
      createFields: createRecord,
      routes: [
        route(
          'overview',
          'Overview',
          'Support performance',
          ['overview-metrics', 'tables-tickets'],
          'wide-first',
          {
            'overview-metrics': metrics('Support metrics', [
              ['open', 'Open requests', 42, '12 high priority'],
              ['resolved', 'Resolved', 128, 'This week'],
              ['response', 'Response (min)', 12, 'Median first response'],
              ['rating', 'Satisfaction', 96, 'Customer rating / 100'],
            ]),
          },
        ),
        route('conversations', 'Conversations', 'Customer inbox', ['collaboration-inbox'], 'stack'),
        route(
          'agents',
          'Agents',
          'Team capacity',
          ['charts-capacity', 'tables-timesheets'],
          'stack',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'acquisition',
    'Meridian Growth Dashboard',
    'Acquisition channels, engagement correlation, conversion stages, and campaign notes.',
    ['growth', 'marketing', 'acquisition'],
    {
      brand: 'Meridian Growth',
      layout: 'topbar',
      primaryAction: 'New campaign note',
      createFields: createRecord,
      routes: [
        route(
          'acquisition',
          'Acquisition',
          'Channel performance',
          ['charts-channels', 'charts-retention'],
          'columns',
        ),
        route(
          'conversion',
          'Conversion',
          'Conversion stages',
          ['charts-funnel', 'overview-goals'],
          'columns',
        ),
        route(
          'campaigns',
          'Campaigns',
          'Campaign planning',
          ['collaboration-board', 'collaboration-notes'],
          'stack',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'reliability',
    'Signal Reliability Dashboard',
    'Service health, percentile latency, deployment state, and security audit events.',
    ['reliability', 'latency', 'services'],
    {
      brand: 'Signal Reliability',
      layout: 'dashboard',
      primaryAction: 'New incident',
      createFields: createRecord,
      routes: [
        route(
          'health',
          'Health',
          'Production reliability',
          ['overview-health', 'charts-latency'],
          'columns',
        ),
        route(
          'deployments',
          'Deployments',
          'Release history',
          ['tables-deployments', 'overview-activity'],
          'stack',
        ),
        route('audit', 'Audit', 'Security events', ['tables-audit', 'settings-security'], 'stack'),
      ],
    },
  ),
  make(
    'dashboards',
    'capacity',
    'Atlas Capacity Dashboard',
    'Team planned hours, time-entry review, work stages, and weekly schedules.',
    ['capacity', 'workload', 'hours'],
    {
      brand: 'Atlas Capacity',
      layout: 'sidebar',
      primaryAction: 'New planning note',
      createFields: createRecord,
      routes: [
        route(
          'capacity',
          'Capacity',
          'Team workload',
          ['charts-capacity', 'tables-timesheets'],
          'stack',
        ),
        route(
          'work',
          'Work',
          'Work in progress',
          ['collaboration-board', 'overview-tasks'],
          'stack',
        ),
        route(
          'schedule',
          'Schedule',
          'Weekly plan',
          ['scheduling-week', 'scheduling-shifts'],
          'stack',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'inventory',
    'Object Inventory Dashboard',
    'Stock availability, demand versus supply, replenishment risks, and fulfillment orders.',
    ['inventory', 'demand', 'stock'],
    {
      brand: 'Object Inventory',
      layout: 'dashboard',
      primaryAction: 'New stock note',
      createFields: createRecord,
      routes: [
        route('stock', 'Stock', 'Inventory health', ['tables-inventory', 'charts-demand'], 'stack'),
        route(
          'risk',
          'Risks',
          'Replenishment risks',
          ['overview-risks', 'collaboration-handoff'],
          'columns',
        ),
        route(
          'orders',
          'Orders',
          'Fulfillment pipeline',
          ['tables-orders', 'charts-regions'],
          'stack',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'portfolio',
    'Pocket Portfolio Dashboard',
    'Asset allocation, account balances, transaction inspection, and cash projections.',
    ['portfolio', 'allocation', 'accounts'],
    {
      brand: 'Pocket Portfolio',
      layout: 'topbar',
      primaryAction: 'New portfolio note',
      createFields: createRecord,
      routes: [
        route(
          'allocation',
          'Allocation',
          'Portfolio overview',
          ['charts-allocation', 'mobile-wallet'],
          'columns',
        ),
        route(
          'transactions',
          'Transactions',
          'Account ledger',
          ['finance-transactions', 'finance-transfer'],
          'columns',
        ),
        route(
          'projection',
          'Projection',
          'Cash planning',
          ['finance-forecast', 'finance-payout'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'objectives',
    'Common Objectives Dashboard',
    'Quarterly objective progress, launch readiness, team decisions, and delivery milestones.',
    ['objectives', 'okr', 'progress'],
    {
      brand: 'Common Objectives',
      layout: 'dashboard',
      primaryAction: 'New objective',
      createFields: createRecord,
      routes: [
        route(
          'objectives',
          'Objectives',
          'Quarterly progress',
          ['overview-goals', 'overview-checklist'],
          'columns',
        ),
        route(
          'delivery',
          'Delivery',
          'Milestones & risks',
          ['scheduling-deadlines', 'overview-risks'],
          'columns',
        ),
        route(
          'decisions',
          'Decisions',
          'Team decisions',
          ['collaboration-poll', 'collaboration-notes'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'fulfillment',
    'Relay Fulfillment Dashboard',
    'Regional dispatch volume, order queues, delivery tracking, and return authorizations.',
    ['fulfillment', 'logistics', 'returns'],
    {
      brand: 'Relay Fulfillment',
      layout: 'dashboard',
      primaryAction: 'New fulfillment note',
      createFields: createRecord,
      routes: [
        route(
          'dispatch',
          'Dispatch',
          'Dispatch operations',
          ['charts-regions', 'tables-orders'],
          'stack',
        ),
        route(
          'deliveries',
          'Deliveries',
          'Active deliveries',
          ['mobile-delivery', 'commerce-order'],
          'columns',
        ),
        route(
          'returns',
          'Returns',
          'Return requests',
          ['commerce-returns', 'collaboration-inbox'],
          'columns',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'quality',
    'Forma Quality Dashboard',
    'Release quality comparison, explicit approval checkpoints, audit evidence, and launch readiness.',
    ['quality', 'accessibility', 'release'],
    {
      brand: 'Forma Quality',
      layout: 'topbar',
      primaryAction: 'New review note',
      createFields: createRecord,
      routes: [
        route(
          'quality',
          'Quality',
          'Release scorecard',
          ['charts-scorecard', 'collaboration-approval'],
          'columns',
        ),
        route(
          'readiness',
          'Readiness',
          'Launch readiness',
          ['overview-checklist', 'overview-risks'],
          'columns',
        ),
        route(
          'evidence',
          'Evidence',
          'Review evidence',
          ['tables-audit', 'collaboration-comments'],
          'stack',
        ),
      ],
    },
  ),
  make(
    'dashboards',
    'spend',
    'Balance Spend Dashboard',
    'Budget allocation, categorized expense claims, payment approval, and billing seats.',
    ['spend', 'expenses', 'budget'],
    {
      brand: 'Balance Spend',
      layout: 'sidebar',
      primaryAction: 'New spending note',
      createFields: createRecord,
      routes: [
        route(
          'budget',
          'Budget',
          'Department spending',
          ['finance-budget', 'tables-expenses'],
          'stack',
        ),
        route(
          'approvals',
          'Approvals',
          'Payment approvals',
          ['finance-approvals', 'finance-expense'],
          'columns',
        ),
        route(
          'billing',
          'Billing',
          'Recurring costs',
          ['finance-billing', 'settings-billing'],
          'columns',
        ),
      ],
    },
  ),
];
