import { seed, row } from './shared';
import type { ProductItem } from '../types';

export const products: readonly ProductItem[] = [
  {
    id: 'headphones',
    name: 'Studio headphones',
    detail: 'Wireless over-ear · 40-hour battery',
    price: 149,
    image:
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=640&q=85',
    options: ['Black', 'Silver'],
  },
  {
    id: 'watch',
    name: 'Field watch',
    detail: 'Stainless steel · 38 mm',
    price: 129,
    image:
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=640&q=85',
    options: ['38 mm', '42 mm'],
  },
  {
    id: 'chair',
    name: 'Task chair',
    detail: 'Molded seat · Solid wood legs',
    price: 240,
    image:
      'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=640&q=85',
    options: ['White', 'Black'],
  },
  {
    id: 'notebook',
    name: 'Pocket notebook',
    detail: '192 pages · Lay-flat binding',
    price: 18,
    image:
      'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=640&q=85',
    options: ['Plain', 'Dotted'],
  },
];
export const workflowBlocks = [
  seed(
    'scheduling-booking',
    'Consultation booking',
    'Choose a calendar date and time slot, provide contact details, and manage the resulting booking.',
    ['booking', 'calendar', 'consultation'],
    {
      family: 'scheduling',
      variant: 'booking',
      title: 'Book a consultation',
      subtitle: '30 minutes · Product design',
      date: '2026-10-01',
      slots: ['09:00', '10:30', '13:00', '14:30', '16:00'],
      items: [row('intro', 'Introduction', 'Meet Avery and discuss your project.', undefined, 30)],
    },
  ),
  seed(
    'scheduling-agenda',
    'Daily agenda',
    'An ordered daily schedule with next-day navigation, event creation, and completion tracking.',
    ['agenda', 'daily', 'events'],
    {
      family: 'scheduling',
      variant: 'agenda',
      title: 'Today’s agenda',
      date: '2026-10-01',
      slots: ['09:00', '10:30', '13:00', '15:00'],
      items: [
        row('standup', 'Team standup', 'Product team · Room A', 'Scheduled', 15, 'Avery', '09:00'),
        row(
          'review',
          'Interface review',
          'Atlas project · Video call',
          'Scheduled',
          45,
          'Sam',
          '10:30',
        ),
        row(
          'interview',
          'Customer interview',
          'Discovery · Video call',
          'Scheduled',
          60,
          'Mina',
          '13:00',
        ),
        row(
          'planning',
          'Sprint planning',
          'Engineering · Room B',
          'Scheduled',
          45,
          'Jordan',
          '15:00',
        ),
      ],
    },
  ),
  seed(
    'scheduling-week',
    'Weekly planning',
    'A five-day schedule with movable event assignments and an event detail dialog.',
    ['week', 'planning', 'calendar'],
    {
      family: 'scheduling',
      variant: 'week',
      title: 'Team week',
      subtitle: 'October 5–9',
      date: '2026-10-05',
      slots: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      items: [
        row('kickoff', 'Project kickoff', 'Atlas · 09:00', 'Mon', 60, 'Avery'),
        row('research', 'Interview round', 'Discovery · 10:00', 'Tue', 90, 'Mina'),
        row('build', 'Build review', 'Platform · 14:00', 'Wed', 45, 'Sam'),
        row('retro', 'Retrospective', 'Team · 15:00', 'Fri', 45, 'Jordan'),
      ],
    },
  ),
  seed(
    'scheduling-availability',
    'Working hours',
    'Configure daily availability switches and time ranges with validated start/end ordering.',
    ['availability', 'hours', 'preferences'],
    {
      family: 'scheduling',
      variant: 'availability',
      title: 'Weekly availability',
      subtitle: 'Europe/London',
      date: '2026-10-01',
      slots: ['09:00', '17:00'],
      items: [
        row('mon', 'Monday', '09:00–17:00', 'Available'),
        row('tue', 'Tuesday', '09:00–17:00', 'Available'),
        row('wed', 'Wednesday', '09:00–13:00', 'Available'),
        row('thu', 'Thursday', '09:00–17:00', 'Available'),
        row('fri', 'Friday', '09:00–16:00', 'Available'),
        row('sat', 'Saturday', 'Unavailable', 'Unavailable'),
        row('sun', 'Sunday', 'Unavailable', 'Unavailable'),
      ],
    },
  ),
  seed(
    'scheduling-shifts',
    'Shift roster',
    'Assign staff to morning, afternoon, and evening shifts with coverage totals.',
    ['shifts', 'staff', 'roster'],
    {
      family: 'scheduling',
      variant: 'shifts',
      title: 'Studio roster',
      subtitle: 'Thursday, October 1',
      date: '2026-10-01',
      slots: ['Morning', 'Afternoon', 'Evening'],
      items: [
        row('avery', 'Avery Morgan', 'Front desk', 'Morning', 8),
        row('jordan', 'Jordan Lee', 'Workshop', 'Afternoon', 8),
        row('riley', 'Riley Brooks', 'Gallery', 'Morning', 6),
        row('alex', 'Alex Rivera', 'Front desk', 'Evening', 6),
      ],
    },
  ),
  seed(
    'scheduling-rooms',
    'Meeting rooms',
    'Inspect room capacity and equipment, pick an available room, and reserve a time.',
    ['rooms', 'resources', 'reservation'],
    {
      family: 'scheduling',
      variant: 'rooms',
      title: 'Find a room',
      date: '2026-10-01',
      slots: ['09:00', '11:00', '13:00', '15:00'],
      items: [
        row('cedar', 'Cedar', 'Screen · Whiteboard · Floor 1', 'Available', 6),
        row('birch', 'Birch', 'Video call · Floor 2', 'Reserved', 4),
        row('oak', 'Oak', 'Screen · Video call · Floor 1', 'Available', 12),
      ],
    },
  ),
  seed(
    'scheduling-deadlines',
    'Milestone timeline',
    'A dated milestone timeline with owner assignment, completion, and overdue filtering.',
    ['timeline', 'milestones', 'deadline'],
    {
      family: 'scheduling',
      variant: 'deadline',
      title: 'Launch milestones',
      date: '2026-10-01',
      slots: ['All', 'Upcoming', 'Complete'],
      items: [
        row(
          'brief',
          'Approve brief',
          'Scope and project outcomes',
          'Complete',
          undefined,
          'Avery',
          '2026-09-28',
        ),
        row(
          'design',
          'Design sign-off',
          'Interface and interaction review',
          'Upcoming',
          undefined,
          'Avery',
          '2026-10-05',
        ),
        row(
          'build',
          'Code freeze',
          'QA and accessibility checks',
          'Upcoming',
          undefined,
          'Sam',
          '2026-10-12',
        ),
        row(
          'launch',
          'Public launch',
          'Release and announcements',
          'Upcoming',
          undefined,
          'Jordan',
          '2026-10-15',
        ),
      ],
    },
  ),
  seed(
    'scheduling-range',
    'Leave request',
    'Choose a start and end date, calculate inclusive days, and submit a leave request.',
    ['date-range', 'leave', 'request'],
    {
      family: 'scheduling',
      variant: 'range',
      title: 'Request time off',
      subtitle: '18 days remaining',
      date: '2026-10-01',
      slots: ['Annual leave', 'Personal day', 'Study leave'],
      items: [row('policy', 'Annual allowance', '25 days per calendar year', 'Available', 18)],
    },
  ),
  seed(
    'scheduling-event',
    'Event registration',
    'Choose a workshop session, set attendee count, and inspect a registration receipt.',
    ['events', 'registration', 'workshop'],
    {
      family: 'scheduling',
      variant: 'event',
      title: 'Studio open day',
      subtitle: 'Saturday, October 10 · Northstar Studio',
      date: '2026-10-10',
      slots: ['10:00', '13:00', '15:30'],
      items: [
        row('print', 'Printmaking', '90 minutes · Materials included', 'Available', 8),
        row('ceramics', 'Ceramics', '120 minutes · Beginner friendly', 'Available', 6),
        row('photo', 'Photography walk', '60 minutes · Bring your camera', 'Available', 12),
      ],
    },
  ),
  seed(
    'scheduling-timezone',
    'Distributed meeting',
    'Compare local times across cities and move the meeting hour to find overlap.',
    ['timezone', 'distributed', 'meeting'],
    {
      family: 'scheduling',
      variant: 'timezone',
      title: 'Find a shared time',
      subtitle: 'Thursday, October 1',
      date: '2026-10-01',
      slots: ['09:00', '12:00', '15:00', '18:00'],
      items: [
        row('london', 'London', 'Europe/London', 'Avery'),
        row('cairo', 'Cairo', 'Africa/Cairo', 'Mina'),
        row('ny', 'New York', 'America/New_York', 'Sam'),
        row('tokyo', 'Tokyo', 'Asia/Tokyo', 'Jordan'),
      ],
    },
  ),

  seed(
    'collaboration-board',
    'Project kanban',
    'Move work between three stages, add tasks, search cards, and inspect card details.',
    ['kanban', 'tasks', 'stages'],
    {
      family: 'collaboration',
      variant: 'board',
      title: 'Atlas board',
      choices: ['To do', 'In progress', 'Done'],
      items: [
        row(
          'research',
          'Research synthesis',
          'Summarize six interviews.',
          'Done',
          undefined,
          'Mina',
        ),
        row(
          'flow',
          'Checkout flow',
          'Review address and payment steps.',
          'In progress',
          undefined,
          'Avery',
        ),
        row(
          'tokens',
          'Token implementation',
          'Map new semantic colors.',
          'In progress',
          undefined,
          'Sam',
        ),
        row(
          'copy',
          'Empty state copy',
          'Write support queue messages.',
          'To do',
          undefined,
          'Jordan',
        ),
        row(
          'qa',
          'Keyboard review',
          'Check focus order in all flows.',
          'To do',
          undefined,
          'Riley',
        ),
      ],
    },
  ),
  seed(
    'collaboration-thread',
    'Team discussion',
    'A timestamped conversation with message composition, sending, and per-message reactions.',
    ['chat', 'thread', 'messages'],
    {
      family: 'collaboration',
      variant: 'thread',
      title: '#product-design',
      subtitle: '5 members',
      items: [
        row(
          'm1',
          'Avery',
          'The new checkout proposal is ready for review.',
          undefined,
          2,
          'Avery',
          '09:42',
        ),
        row(
          'm2',
          'Sam',
          'I will check the keyboard flow this afternoon.',
          undefined,
          1,
          'Sam',
          '09:45',
        ),
        row(
          'm3',
          'Mina',
          'The research notes are linked in the project brief.',
          undefined,
          0,
          'Mina',
          '09:48',
        ),
      ],
    },
  ),
  seed(
    'collaboration-comments',
    'Document comments',
    'Threaded review comments with resolution, reply composition, and unresolved filtering.',
    ['comments', 'review', 'resolve'],
    {
      family: 'collaboration',
      variant: 'comments',
      title: 'Review comments',
      subtitle: 'Checkout specification',
      items: [
        row(
          'c1',
          'Address validation',
          'Can we preserve the address if payment fails?',
          'Open',
          undefined,
          'Avery',
          '09:30',
        ),
        row(
          'c2',
          'Delivery estimate',
          'Use a date range rather than a single date.',
          'Open',
          undefined,
          'Jordan',
          '10:10',
        ),
        row(
          'c3',
          'Error recovery',
          'The retry state now retains the form values.',
          'Resolved',
          undefined,
          'Sam',
          '10:24',
        ),
      ],
    },
  ),
  seed(
    'collaboration-members',
    'Project members',
    'Search collaborators, edit project roles, invite a teammate, and remove members.',
    ['members', 'roles', 'invite'],
    {
      family: 'collaboration',
      variant: 'members',
      title: 'Project access',
      subtitle: 'Atlas redesign',
      choices: ['Owner', 'Editor', 'Commenter', 'Viewer'],
      items: [
        row('avery', 'Avery Morgan', 'avery@northstar.example', 'Owner'),
        row('sam', 'Sam Chen', 'sam@northstar.example', 'Editor'),
        row('mina', 'Mina Patel', 'mina@northstar.example', 'Commenter'),
        row('jordan', 'Jordan Lee', 'jordan@northstar.example', 'Viewer'),
      ],
    },
  ),
  seed(
    'collaboration-approval',
    'Approval chain',
    'Review a design submission and approve or request changes at individual checkpoints.',
    ['approval', 'review', 'chain'],
    {
      family: 'collaboration',
      variant: 'approval',
      title: 'Release approval',
      subtitle: 'Autumn storefront · Version 4',
      items: [
        row(
          'design',
          'Design review',
          'Layout, typography, and mobile states.',
          'Approved',
          undefined,
          'Avery',
        ),
        row(
          'access',
          'Accessibility review',
          'Keyboard, contrast, and screen reader audit.',
          'Pending',
          undefined,
          'Sam',
        ),
        row(
          'content',
          'Content review',
          'Product descriptions and policy copy.',
          'Pending',
          undefined,
          'Jordan',
        ),
      ],
    },
  ),
  seed(
    'collaboration-notes',
    'Meeting notes',
    'A structured note editor with editable decisions and assignable action items.',
    ['notes', 'meeting', 'actions'],
    {
      family: 'collaboration',
      variant: 'notes',
      title: 'Product sync',
      subtitle: 'October 1 · Avery, Sam, Mina',
      items: [
        row(
          'summary',
          'Summary',
          'Ship the smaller checkout flow first. Keep account creation optional.',
        ),
        row('decision', 'Decision', 'Use one address step and a separate payment step.'),
        row('action1', 'Prototype address recovery', 'Due October 3', 'Open', undefined, 'Avery'),
        row('action2', 'Review validation messages', 'Due October 4', 'Open', undefined, 'Sam'),
      ],
    },
  ),
  seed(
    'collaboration-poll',
    'Team decision poll',
    'Vote on a team choice, change your vote, and compare response counts.',
    ['poll', 'vote', 'decision'],
    {
      family: 'collaboration',
      variant: 'poll',
      title: 'When should we run the review?',
      subtitle: '8 responses · Closes Friday',
      choices: ['Monday morning', 'Tuesday afternoon', 'Thursday morning'],
      items: [
        row('mon', 'Monday morning', '09:30–10:30', undefined, 3),
        row('tue', 'Tuesday afternoon', '14:00–15:00', undefined, 4),
        row('thu', 'Thursday morning', '10:00–11:00', undefined, 1),
      ],
    },
  ),
  seed(
    'collaboration-inbox',
    'Shared inbox',
    'A two-pane customer inbox with conversation selection, read state, and reply composition.',
    ['inbox', 'support', 'reply'],
    {
      family: 'collaboration',
      variant: 'inbox',
      title: 'Team inbox',
      items: [
        row(
          'i1',
          'Alex Rivera',
          'Can I change my delivery address?',
          'Unread',
          undefined,
          'Orders',
          '09:42',
        ),
        row(
          'i2',
          'Taylor Kim',
          'Thanks, the replacement arrived today.',
          'Read',
          undefined,
          'Returns',
          '09:15',
        ),
        row(
          'i3',
          'Casey Park',
          'Could you send a VAT invoice?',
          'Unread',
          undefined,
          'Billing',
          'Yesterday',
        ),
        row(
          'i4',
          'Morgan Reed',
          'Is the silver watch back in stock?',
          'Read',
          undefined,
          'Products',
          'Yesterday',
        ),
      ],
    },
  ),
  seed(
    'collaboration-handoff',
    'Shift handoff',
    'A handoff checklist with critical notes, acknowledgment, and an outgoing shift summary.',
    ['handoff', 'operations', 'acknowledge'],
    {
      family: 'collaboration',
      variant: 'handoff',
      title: 'Evening handoff',
      subtitle: 'Jordan → Riley · October 1',
      items: [
        row('stock', 'Check incoming stock', 'Two cartons expected by 18:00.', 'Open'),
        row('return', 'Process return ORD-824', 'Customer label is ready at the desk.', 'Open'),
        row('room', 'Prepare workshop room', '12 seats and materials for printmaking.', 'Complete'),
        row(
          'close',
          'Confirm closing checklist',
          'Lock gallery, storage, and back entrance.',
          'Open',
        ),
      ],
    },
  ),
  seed(
    'collaboration-files',
    'Shared deliverables',
    'Review deliverable versions, approve files, and download a shareable manifest.',
    ['files', 'versions', 'deliverables'],
    {
      family: 'collaboration',
      variant: 'files',
      title: 'Project deliverables',
      items: [
        row('spec', 'Checkout specification', 'Version 4 · 24 pages', 'Review', 4, 'Avery'),
        row('assets', 'Product image set', 'Version 2 · 18 images', 'Approved', 2, 'Jordan'),
        row('tokens', 'Token mapping', 'Version 3 · 42 tokens', 'Review', 3, 'Sam'),
        row('research', 'Research summary', 'Version 1 · 8 pages', 'Approved', 1, 'Mina'),
      ],
    },
  ),

  seed(
    'commerce-product',
    'Product detail',
    'Inspect a product photo, select a variant and quantity, and add it to a working cart.',
    ['product', 'variants', 'quantity'],
    { family: 'commerce', variant: 'product', title: 'Studio headphones', products: [products[0]] },
  ),
  seed(
    'commerce-catalog',
    'Product collection',
    'Search and sort a photographic product collection, filter price ranges, and track cart quantities.',
    ['catalog', 'search', 'sort'],
    {
      family: 'commerce',
      variant: 'catalog',
      title: 'Everyday essentials',
      subtitle: 'Objects made for use.',
      products,
    },
  ),
  seed(
    'commerce-cart',
    'Shopping cart',
    'Change quantities, remove items, calculate shipping, and review a checkout receipt.',
    ['cart', 'shipping', 'totals'],
    {
      family: 'commerce',
      variant: 'cart',
      title: 'Your bag',
      products: [products[0], products[3]],
    },
  ),
  seed(
    'commerce-checkout',
    'Checkout details',
    'Delivery and payment-method selection alongside a calculated order summary.',
    ['checkout', 'address', 'payment'],
    {
      family: 'commerce',
      variant: 'checkout',
      title: 'Checkout',
      products: [products[1], products[3]],
    },
  ),
  seed(
    'commerce-order',
    'Order tracker',
    'Inspect an order’s items and delivery stages, advance local fulfillment, and download a receipt.',
    ['order', 'tracking', 'receipt'],
    {
      family: 'commerce',
      variant: 'order',
      title: 'Order OBJ-1042',
      subtitle: 'Placed October 1, 2026',
      products: [products[0], products[1]],
    },
  ),
  seed(
    'commerce-plans',
    'Workspace plans',
    'Compare plan capabilities, switch billing intervals, and choose a workspace plan.',
    ['plans', 'subscription', 'billing'],
    {
      family: 'commerce',
      variant: 'plans',
      title: 'Workspace plans',
      products: [
        { id: 'solo', name: 'Solo', detail: '1 workspace · 3 projects · 2 GB storage', price: 9 },
        {
          id: 'team',
          name: 'Team',
          detail: '5 workspaces · Unlimited projects · 50 GB storage',
          price: 24,
        },
        {
          id: 'studio',
          name: 'Studio',
          detail: 'Unlimited workspaces · Role controls · 200 GB storage',
          price: 49,
        },
      ],
    },
  ),
  seed(
    'commerce-bundle',
    'Build a desk set',
    'Configure a product bundle with individual inclusion toggles and a live bundle discount.',
    ['bundle', 'configuration', 'discount'],
    {
      family: 'commerce',
      variant: 'bundle',
      title: 'Make your desk set',
      subtitle: 'Save 15% when you choose two or more.',
      products: [products[0], products[2], products[3]],
    },
  ),
  seed(
    'commerce-discount',
    'Promotion calculator',
    'Apply a disclosed local promotion code, compare before/after totals, and remove the discount.',
    ['promotion', 'coupon', 'calculator'],
    {
      family: 'commerce',
      variant: 'discount',
      title: 'Order summary',
      subtitle: 'Autumn offer · Code AUTUMN10',
      products: [products[0], products[3]],
    },
  ),
  seed(
    'commerce-returns',
    'Return request',
    'Select returned items, provide a reason, and create an inspectable return authorization.',
    ['returns', 'reason', 'selection'],
    {
      family: 'commerce',
      variant: 'returns',
      title: 'Return an item',
      subtitle: 'Order OBJ-1028 · Delivered September 24',
      products: [products[0], products[1], products[3]],
    },
  ),
  seed(
    'commerce-compare',
    'Product comparison',
    'Compare inspectable products across price, material details, and selectable variants.',
    ['comparison', 'products', 'selection'],
    {
      family: 'commerce',
      variant: 'compare',
      title: 'Compare your shortlist',
      products: [products[0], products[1], products[2]],
    },
  ),
];
