import ts from 'typescript';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
const slots = new Set();
for (const file of readdirSync('src/ui').filter((name) => name.endsWith('.tsx'))) {
  const source = ts.createSourceFile(
    file,
    readFileSync(`src/ui/${file}`, 'utf8'),
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX,
  );
  const visit = (node) => {
    if (
      ts.isCallExpression(node) &&
      ts.isIdentifier(node.expression) &&
      node.expression.text === 'styles' &&
      ts.isStringLiteral(node.arguments[0])
    )
      slots.add(node.arguments[0].text);
    ts.forEachChild(node, visit);
  };
  visit(source);
}
writeFileSync(
  'src/ui/slots.ts',
  `// Generated by scripts/generate-slots.mjs.\nexport const styleSlots = ${JSON.stringify([...slots].sort(), null, 2)} as const;\nexport type StyleSlot = typeof styleSlots[number];\n`,
);
